// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Minimal native crate for the `native_scalar_pkg` fixture (@PLN26).
//!
//! Exports one scalar `#native` symbol, `n_native_answer`, bound to the loft
//! `native_answer()` wrapper.  A no-arg integer return — the cheapest possible
//! native shape — so this fixture stays cheap to build while still covering the
//! C-ABI exec path (and the Windows import-library link + DLL staging, @PLN26
//! phase 4) on `--native`, plus the `--interpret` dlopen-dispatch path.
//!
//! Plan-74: `n_native_answer` carries `#[loft_native]`, so the interpreter
//! dispatches it through the generated uniform marshal bridge — the same path
//! every other native library uses now that the legacy `dispatch_call` arms are
//! gone.  `build.rs` source-scans the loft decl (bare `#native` → `n_<fn>`) and
//! emits both the raw register list and the bridge register list.

#![allow(clippy::missing_safety_doc)]

use loft_ffi::{LoftRef, LoftStore};
use loft_ffi_macros::loft_native;

// `i64`, NOT `i32`: the loft declaration types this `integer`, and loft maps `integer`
// to `i64` on the C boundary (doc/claude/PACKAGES.md), emitting the extern from the
// DECLARATION and calling it directly.  A narrower Rust return is an ABI mismatch, not
// a harmless narrowing — on x86-64 SysV an `i32` return leaves the upper half of `rax`
// undefined.  42 happens to survive it; `n_native_sentinel` below does not, which is
// why it exists.
#[loft_native]
#[no_mangle]
pub extern "C" fn n_native_answer() -> i64 {
    42
}

/// Returns -1 — the value that makes an integer-width ABI mismatch observable.
#[loft_native]
#[no_mangle]
pub extern "C" fn n_native_sentinel() -> i64 {
    -1
}

/// Returns `[100, 101, …, 100 + n - 1]`, allocated in the caller's loft store.
///
/// The store-handle shape of this fixture: a vector return makes loft's codegen wrap the
/// call in `loft::native_call::enter` / `build_store`, which the scalar fns above never
/// reach.  Deterministic so the test can assert the elements, not just the count.
/// A non-positive or null `n` yields an empty vector.
#[loft_native]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_native_span(mut store: LoftStore, n: i64) -> LoftRef {
    let count = if n == i64::MIN || n <= 0 { 0 } else { n as usize };
    // 8-byte slots: loft's `vector<integer>` narrow-record layout.
    let mut vec = unsafe { store.alloc_vector(8, count as u32) };
    for i in 0..count {
        unsafe { store.vector_push_long(&mut vec, 100 + i as i64) };
    }
    vec
}

// The `loft_ffi::loft_register! { … }` + `loft_register_bridges! { … }`
// invocations are GENERATED by `build.rs` (via
// `loft-ffi-build::generate_register_from_loft_with_bridges`) scanning this
// crate's loft sources for `#native` annotations.
include!(concat!(env!("OUT_DIR"), "/loft_register_gen.rs"));
