[package]
name = "loft-web"
version = "0.1.0"
edition = "2024"
license = "LGPL-3.0-or-later"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ureq = { version = "2", features = ["cookies"] }
base64 = "0.22"
loft-ffi = { path = "../../../loft-ffi" }
loft-ffi-macros = { path = "../../../loft-ffi-macros" }

[build-dependencies]
loft-ffi-build = { path = "../../../loft-ffi-build" }
