// Auto-generated by `loft generate`. Fill in the todo!() bodies.
// Functions with text parameters use loft_ffi helpers.
// Struct field offsets are in *_fields modules.

#![allow(clippy::missing_safety_doc)]

// Add to Cargo.toml: loft-ffi = { path = "../../../loft-ffi" }

/// Field offsets for struct `image`.
/// Record size: 16 bytes (2 words).
#[allow(dead_code)]
pub mod image_fields {
    pub const NAME: u16 = 0; // text (record ref)
    pub const WIDTH: u16 = 4; // integer
    pub const HEIGHT: u16 = 8; // integer
    pub const DATA: u16 = 12; // vector ref
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_load_png(
    store: loft_ffi::LoftStore,
    path_ptr: *const u8, path_len: usize,
    image: loft_ffi::LoftRef /* Image */,
) -> bool {
    let path = unsafe { loft_ffi::text(path_ptr, path_len) };
    todo!("implement n_load_png(path, image)")
}
