#!/usr/bin/env bash
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# deploy-library-ci — replace every loft-lang/loft-libs-* repo's library-ci.yml with
# a thin caller of the unified reusable workflow (.github/workflows/library-ci-reusable.yml
# in loft-lang/loft).  Each repo's packages are computed from its actual package dirs
# (a dir with a loft.toml), so the caller stays correct even as packages are added.
#
# WHY: the per-repo copies had drifted — a stale `jjstwerff/loft` checkout URL in most,
# an incomplete package matrix in some, and NO CI at all in loft-libs-docs.  Centralising
# the build logic fixes all of that in one place.
#
# PREREQUISITE: the reusable workflow must already be on loft-lang/loft@main (the callers
# reference it at @main).  Run this AFTER that lands.
#
# Pushes ONE branch per repo; it does NOT open PRs — landing is the maintainer's call.
#
# Usage:
#   scripts/deploy-library-ci.sh [--branch <name>] [--dry-run]
set -euo pipefail

ORG=loft-lang
BRANCH=unify-library-ci
DRY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --branch) BRANCH="$2"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

NAME=$(git config user.name  || echo "loft maintainer")
EMAIL=$(git config user.email || echo "maintainer@loft-lang.org")
tmp=$(mktemp -d -t deploy-library-ci.XXXXXX)
trap 'rm -rf "$tmp"' EXIT

repos=$(gh api "orgs/$ORG/repos?per_page=100" --jq '.[].name' | grep '^loft-libs-' || true)
[ -n "$repos" ] || { echo "no loft-libs-* repos found (is gh authenticated?)" >&2; exit 1; }

for r in $repos; do
  git clone --quiet --depth 1 "https://github.com/$ORG/$r.git" "$tmp/$r"
  (
    cd "$tmp/$r"
    pkgs=$(for d in */; do [ -f "${d}loft.toml" ] && basename "$d"; done | sort)
    if [ -z "$pkgs" ]; then echo "  $r: no packages — skip"; exit 0; fi
    json=$(printf '%s\n' $pkgs | python3 -c 'import sys,json; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')

    mkdir -p .github/workflows
    cat > .github/workflows/library-ci.yml <<YAML
# Generated by loft-lang/loft scripts/deploy-library-ci.sh — the UNIFIED library CI.
# The build logic and the loft checkout URL live in the reusable workflow; this file
# only lists this repo's packages.  To change the gate, edit the reusable in
# loft-lang/loft, not these copies.
name: library-ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    uses: $ORG/loft/.github/workflows/library-ci-reusable.yml@main
    with:
      packages: '$json'
YAML

    git add .github/workflows/library-ci.yml         # stage so new files (repos with no CI) are detected too
    if git diff --cached --quiet; then
      echo "  $r: already unified — skip"; exit 0
    fi
    if [ "$DRY" = 1 ]; then
      echo "  $r: WOULD push $BRANCH (packages $json)"; exit 0
    fi
    git config user.name  "$NAME"
    git config user.email "$EMAIL"
    git checkout -q -b "$BRANCH"
    git commit -q -m "ci: adopt the unified reusable library-ci (packages: $json)"
    git push -q -u origin "$BRANCH"
    echo "  $r: pushed $BRANCH (packages $json) — open a PR to land"
  )
done
echo "done. Open a PR per repo (or: gh pr create -R $ORG/<repo> -H $BRANCH)."
