#!/usr/bin/env python3
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Generate doc/claude/LIBRARIES.md — the in-repo, agent-facing catalogue of
# every library installable from the loft registry.  The point is
# discoverability: an agent working in this repo must SEE that a registered
# library already does X before reimplementing it (duplicate code, new bugs).
#
# This is the single registry catalogue kept in-repo — it stops an agent from
# reinventing a published library.  (A separate user-facing table generator,
# scripts/gen_library_catalog.py → doc/library-catalog.md, was retired
# 2026-07-02: it was a stale, un-CI-guarded duplicate of this one.)
#
# Source order:
#   1. --index <path>        explicit local index.json (CI uses the committed snapshot)
#   2. the live registry URL (default)
#   3. on live-fetch failure: the local working copy at
#      /home/jurjen/workspace/registry/index.json, if present
#   else: exit non-zero with a clear message.
#
# Output is idempotent — running twice yields byte-identical LIBRARIES.md (and,
# in --refresh-snapshot mode, a byte-identical snapshot), so the CI staleness
# guard is a clean diff check.
#
# Usage:
#   scripts/gen-library-catalogue.py                       # live → doc/claude/LIBRARIES.md
#   scripts/gen-library-catalogue.py --index <path>        # read a local index.json
#   scripts/gen-library-catalogue.py --check               # CI gate: exit 1 on drift
#   scripts/gen-library-catalogue.py --refresh-snapshot    # also rewrite the committed snapshot

from __future__ import annotations

import argparse
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

LIVE_URL = "https://raw.githubusercontent.com/loft-lang/registry/main/index.json"
# Working-copy fallback when the live fetch fails (offline / CDN blip).
LOCAL_FALLBACK = Path("/home/jurjen/workspace/registry/index.json")

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "doc" / "claude" / "LIBRARIES.md"
# Committed snapshot CI generates from (deterministic, no network in CI).
SNAPSHOT = REPO_ROOT / "doc" / "claude" / "registry-index-snapshot.json"
# @PLN112 phase 2 — per-lib `origin/main` API (the `unreleased` tier), committed for
# determinism; built by scripts/refresh-unreleased.py.
UNRELEASED = REPO_ROOT / "doc" / "claude" / "unreleased-snapshot.json"


def _norm_sig(sig: str) -> str:
    """Whitespace-normalise a signature so `published` and `unreleased` compare cleanly."""
    return " ".join((sig or "").split())

HEADER = "<!-- generated by scripts/gen-library-catalogue.py — do not hand-edit -->"


def semver_key(version: str) -> list[int]:
    """Numeric semver sort key: split on '.', compare each part as an int.

    Non-numeric / prerelease parts (e.g. '1.0.0-rc1') compare as 0 for their
    segment, so a clean release sorts at or above its prereleases — good enough
    for picking the latest published version.
    """
    out: list[int] = []
    for part in version.split("."):
        digits = ""
        for ch in part:
            if ch.isdigit():
                digits += ch
            else:
                break
        out.append(int(digits) if digits else 0)
    return out


def latest_version(versions: dict[str, Any]) -> str:
    """Return the highest version by NUMERIC semver sort (not string sort)."""
    return max(versions, key=semver_key)


def use_hint(version_entry: dict[str, Any]) -> str:
    """Auto-use libraries (a non-empty `triggers` list on the latest version)
    need no `use` statement — calling the method pulls them in.  Everything
    else needs an explicit `use <name>;`."""
    triggers = version_entry.get("triggers") or []
    if triggers:
        return "auto-use (no `use` needed)"
    return "`use {name};`"  # filled in per-library below


def render(index: dict[str, Any], unreleased: dict[str, Any] | None = None) -> str:
    unreleased = unreleased or {}
    packages: dict[str, Any] = index.get("packages", {})
    n = len(packages)

    # Group by EACH category (a package can list several), sorted alphabetically.
    by_cat: dict[str, list[str]] = {}
    for name in packages:
        cats = packages[name].get("categories") or ["uncategorised"]
        for cat in cats:
            by_cat.setdefault(cat, []).append(name)

    lines: list[str] = []
    lines.append(HEADER)
    lines.append("")
    lines.append("# Installable libraries (loft registry)")
    lines.append("")
    lines.append(
        f"**{n} libraries are installable from the registry — check here BEFORE "
        f"implementing functionality, so you don't reimplement existing code.**"
    )
    lines.append("")
    lines.append(
        "How to use one: `loft install <name>`, then `use <name>;` in your program "
        "— or, for an auto-use library, just call the method (no `use` needed)."
    )
    lines.append("")
    lines.append(
        "A package may appear under more than one category (it is listed under each "
        "of its categories)."
    )
    lines.append("")

    for cat in sorted(by_cat):
        lines.append(f"## {cat}")
        lines.append("")
        for name in sorted(by_cat[cat]):
            pkg = packages[name]
            versions = pkg.get("versions", {})
            latest = latest_version(versions)
            entry = versions[latest]
            description = (pkg.get("description") or "").strip()
            homepage = (pkg.get("homepage") or "").strip()

            triggers = entry.get("triggers") or []
            hint = (
                "auto-use (no `use` needed)" if triggers else f"`use {name};`"
            )

            # The entry now carries the LATEST version + its public API surface
            # (`entry['api']` — the SAME sigs `loft api <name>` prints and the
            # registry `pkg_api_items` extractor produces).  So an agent finds a
            # library's exact functions HERE, in one always-regenerated place,
            # instead of reading a lib clone or the installed copy (both go stale
            # and lie — a merged rename reads as "never happened").  The cost is a
            # regen when a library publishes a new API; the CI `--check` drift gate
            # keeps this file honest so the staleness can't hide.
            api = entry.get("api") or []
            unrel_api = (unreleased.get(name) or {}).get("api") or []
            # @PLN112 phase 2 — the `unreleased` tier: functions on the lib's origin/main not
            # yet in the published version. Diff ONLY when the registry recorded a published
            # API; otherwise the "diff" would falsely tag every origin/main function
            # unreleased (a registry data gap, not divergence — e.g. graphics 0.4.3 records
            # 0 sigs), so we show origin/main plain with a note instead. (Removals / breaking
            # changes are api-compat, phase 5.)
            if api:
                pub_sigs = {_norm_sig(i.get("sig", "")) for i in api}
                unrel_only = [
                    i for i in unrel_api
                    if _norm_sig(i.get("sig", "")) and _norm_sig(i.get("sig", "")) not in pub_sigs
                ]
                note = f" · origin/main: +{len(unrel_only)} unreleased" if unrel_only else ""
                show = [(i, False) for i in api] + [(i, True) for i in unrel_only]
            elif unrel_api:
                note = " · API from origin/main (registry `api` not recorded)"
                show = [(i, False) for i in unrel_api]
            else:
                note = ""
                show = []
            lines.append(f"- **{name}** — {description}  · v{latest} · {hint}{note}")
            lines.append(f"  · loft install {name} · [source]({homepage})")
            if show:
                lines.append("  · public API:")
                for item, is_unrel in show:
                    sig = (item.get("sig") or "").strip()
                    if not sig:
                        continue
                    tag = "  🟢 unreleased (origin/main, not yet published)" if is_unrel else ""
                    lines.append(f"    - `{sig}`{tag}")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def load_index(args: argparse.Namespace) -> dict[str, Any]:
    """Resolve the registry index per the documented source order."""
    if args.index:
        path = Path(args.index)
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except OSError as exc:
            sys.exit(f"gen-library-catalogue: cannot read --index {path}: {exc}")

    # No explicit index: try live, fall back to the local working copy.
    try:
        with urllib.request.urlopen(LIVE_URL, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as exc:  # noqa: BLE001 — any network/parse error → fallback
        sys.stderr.write(
            f"gen-library-catalogue: live fetch failed ({exc}); "
            f"trying local fallback {LOCAL_FALLBACK}\n"
        )
        if LOCAL_FALLBACK.exists():
            return json.loads(LOCAL_FALLBACK.read_text(encoding="utf-8"))
        sys.exit(
            "gen-library-catalogue: live fetch failed and no local fallback "
            f"at {LOCAL_FALLBACK} — pass --index <path> to a local index.json."
        )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--index", help="path to a local index.json (default: live URL)")
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if doc/claude/LIBRARIES.md is out of date (no write)",
    )
    ap.add_argument(
        "--refresh-snapshot",
        action="store_true",
        help="also rewrite the committed registry-index-snapshot.json",
    )
    args = ap.parse_args()

    index = load_index(args)
    # The committed unreleased snapshot (phase 2). Read from disk (not the network) so both
    # a normal regen and `--check` are deterministic against the same committed data.
    unreleased = (
        json.loads(UNRELEASED.read_text(encoding="utf-8")) if UNRELEASED.exists() else {}
    )
    rendered = render(index, unreleased)

    if args.check:
        if not OUTPUT.exists():
            sys.stderr.write(f"gen-library-catalogue --check: {OUTPUT} missing\n")
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            sys.stderr.write(
                f"gen-library-catalogue --check: {OUTPUT} is out of date.\n"
                "  Run `make libcatalogue` and commit the result.\n"
            )
            return 1
        print(f"gen-library-catalogue --check: {OUTPUT} is up to date.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"gen-library-catalogue: wrote {OUTPUT} ({len(index.get('packages', {}))} libraries)")

    if args.refresh_snapshot:
        # Pretty-print stably so the snapshot diff is reviewable + idempotent.
        SNAPSHOT.write_text(
            json.dumps(index, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"gen-library-catalogue: refreshed snapshot {SNAPSHOT}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
