#!/usr/bin/env python3
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# @PLAN12 Phase 6.15 — library catalog generator.
#
# Pulls `index.json` (and optionally `advisories.json`) from the
# loft package registry and emits `doc/library-catalog.md` — a
# user-facing browseable catalog sorted by category.  Auto-update
# wire-up via the registry repo's CI is a follow-up; this script
# is the engine.
#
# Usage:
#   scripts/gen_library_catalog.py                        # fetch live + write doc/library-catalog.md
#   scripts/gen_library_catalog.py --check                # CI gate: exit 1 if drift
#   scripts/gen_library_catalog.py --source <path|url>    # use a specific index.json
#   scripts/gen_library_catalog.py --out <path>           # override output path
#
# By default reads $LOFT_REGISTRY_URL if set, else the canonical
# registry URL.  Honours `file://` source URLs for offline /
# mock-registry use.

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path
from typing import Any

DEFAULT_REGISTRY_URL = (
    "https://raw.githubusercontent.com/loft-lang/registry/main/index.json"
)
DEFAULT_OUTPUT = "doc/library-catalog.md"


def fetch(url: str) -> str:
    """Fetch a JSON resource as a text string.  Handles http(s)://
    and file:// URLs."""
    if url.startswith("file://"):
        path = url[len("file://"):]
        return Path(path).read_text(encoding="utf-8")
    # Plain path → treat as file
    if not url.startswith(("http://", "https://")):
        return Path(url).read_text(encoding="utf-8")
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def compare_semver(a: str, b: str) -> int:
    """Return -1/0/1 for a < / == / > b.  Same shape as the loft
    binary's `registry_index::compare_semver`."""
    def parts(v: str) -> list[int]:
        # Strip prerelease tags; treat them as -1 for ordering purposes.
        core = v.split("-")[0]
        return [int(x) if x.isdigit() else 0 for x in core.split(".")]

    pa, pb = parts(a), parts(b)
    while len(pa) < len(pb):
        pa.append(0)
    while len(pb) < len(pa):
        pb.append(0)
    for x, y in zip(pa, pb):
        if x < y:
            return -1
        if x > y:
            return 1
    return 0


def latest_active(versions: dict[str, Any], yanked: list[str]) -> str | None:
    """Return the highest-versioned non-yanked entry's semver, or
    None if every version is yanked."""
    yanked_set = set(yanked)
    candidates = [v for v in versions if v not in yanked_set]
    if not candidates:
        return None
    best = candidates[0]
    for v in candidates[1:]:
        if compare_semver(v, best) > 0:
            best = v
    return best


def emit(idx: dict[str, Any]) -> str:
    """Render the catalog page from a parsed index."""
    packages = idx.get("packages", {})
    if not packages:
        return "# Loft library catalog\n\nNo packages in registry yet.\n"

    # Group by primary category (first entry in `categories`); packages
    # with no category land in "uncategorised".
    by_cat: dict[str, list[tuple[str, dict[str, Any]]]] = {}
    for name in sorted(packages.keys()):
        pkg = packages[name]
        cats = pkg.get("categories", []) or []
        primary = cats[0] if cats else "uncategorised"
        by_cat.setdefault(primary, []).append((name, pkg))

    out: list[str] = []
    out.append("<!-- Auto-generated by scripts/gen_library_catalog.py — do not edit by hand. -->")
    out.append("<!-- Source: $LOFT_REGISTRY_URL or canonical registry. -->")
    out.append("")
    out.append("# Loft library catalog")
    out.append("")
    out.append(
        "Every library published to the loft registry.  Install one with "
        "`loft install <name>` or just `use <name>;` in a script (auto-installs "
        "on first run — see [PACKAGES.md] for the resolution model)."
    )
    out.append("")
    out.append(f"Registry source: `{idx.get('updated', 'unknown')}`.")
    out.append("")

    total_active = 0
    total_yanked = 0
    for cat in sorted(by_cat.keys()):
        out.append(f"## {cat}")
        out.append("")
        out.append("| Library | Latest | Description |")
        out.append("|---|---|---|")
        for name, pkg in by_cat[cat]:
            versions = pkg.get("versions", {}) or {}
            yanked = pkg.get("yanked", []) or []
            best = latest_active(versions, yanked)
            if best is None:
                total_yanked += len(versions)
                latest_cell = "*(all versions yanked)*"
            else:
                total_active += 1
                latest_cell = best
            description = pkg.get("description", "").strip() or "—"
            # Escape pipe chars for table cells.
            description = description.replace("|", "\\|")
            homepage = pkg.get("homepage", "").strip()
            if homepage:
                name_cell = f"[{name}]({homepage})"
            else:
                name_cell = name
            out.append(f"| {name_cell} | {latest_cell} | {description} |")
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        f"**{total_active} active package(s)** across {len(by_cat)} categor(ies)."
    )
    if total_yanked:
        out.append(
            f"  {total_yanked} fully-yanked version(s) elided from this listing — "
            f"run `loft audit` to see the per-version status."
        )
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description="@PLAN12 Phase 6.15 library catalog generator")
    ap.add_argument(
        "--source",
        default=os.environ.get("LOFT_REGISTRY_URL") or DEFAULT_REGISTRY_URL,
        help="URL or local path of index.json (default: $LOFT_REGISTRY_URL or canonical)",
    )
    ap.add_argument(
        "--out",
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT})",
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated output differs from the committed file",
    )
    args = ap.parse_args()

    try:
        raw = fetch(args.source)
    except Exception as e:  # noqa: BLE001
        print(f"gen_library_catalog: fetch failed: {e}", file=sys.stderr)
        return 1

    try:
        idx = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"gen_library_catalog: source is not valid JSON: {e}", file=sys.stderr)
        return 1

    if idx.get("schema_version") != 1:
        print(
            f"gen_library_catalog: unsupported schema_version "
            f"{idx.get('schema_version')!r}",
            file=sys.stderr,
        )
        return 1

    rendered = emit(idx)
    out_path = Path(args.out)

    if args.check:
        if not out_path.exists():
            print(f"gen_library_catalog --check: {out_path} missing", file=sys.stderr)
            return 1
        committed = out_path.read_text(encoding="utf-8")
        if committed != rendered:
            print(
                f"gen_library_catalog --check: {out_path} is out of sync with the registry.",
                file=sys.stderr,
            )
            print(
                "  Run `scripts/gen_library_catalog.py` to refresh + commit the diff.",
                file=sys.stderr,
            )
            return 1
        print(f"gen_library_catalog --check: {out_path} matches the registry.")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")
    print(f"gen_library_catalog: wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
