#!/usr/bin/env python3
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Render one Markdown design document as Typst, so it can be printed as its own PDF.

    scripts/md2typ.py doc/claude/WEB_STACK.md doc/web-stack.typ
    typst compile doc/web-stack.typ doc/web-stack.pdf

The Markdown file stays the single source: this reads it and writes a `.typ` beside the
other generated Typst, the same way `gendoc` writes `doc/loft-reference.typ`.  Nothing
is maintained twice, so the document cannot drift from its own PDF.

Covers the constructs the `doc/claude/` design documents actually use — headings, fenced
code, tables, lists, block quotes, rules, and inline emphasis / code / links.  Anything
else passes through as text, which is the right failure: an unhandled construct prints
plainly instead of breaking the compile.
"""

import html
import re
import sys

# Typst's markup gives these characters meaning, so text destined for markup escapes them.
# Raw spans (`code`) and URLs are handled separately and must NOT go through this.
_SPECIAL = "\\$#*_`<>@=-+/[]"


def esc(text: str) -> str:
    """Escape one run of plain text for Typst markup."""
    return "".join("\\" + c if c in _SPECIAL else c for c in text)


def inline(text: str) -> str:
    """Convert inline Markdown — code, bold, italic, links — to Typst.

    Code spans are extracted FIRST and put back last, because their contents are raw and
    must not be escaped: a `*` inside `` `a*b` `` is a literal asterisk, not emphasis.
    """
    codes: list[str] = []

    def take_code(m: re.Match) -> str:
        codes.append(m.group(1))
        return f"\x00{len(codes) - 1}\x00"

    text = re.sub(r"`([^`]+)`", take_code, text)

    links: list[str] = []

    def take_link(m: re.Match) -> str:
        label, target = m.group(1), m.group(2)
        # A relative link has no meaning in a PDF; keep the label and drop the target.
        if "://" in target:
            links.append(f'#link("{target}")[{inline(label)}]')
        else:
            links.append(inline(label))
        return f"\x01{len(links) - 1}\x01"

    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", take_link, text)

    marks: list[str] = []

    def take_bold(m: re.Match) -> str:
        marks.append("*" + esc(m.group(1)) + "*")
        return f"\x02{len(marks) - 1}\x02"

    def take_italic(m: re.Match) -> str:
        marks.append("_" + esc(m.group(1)) + "_")
        return f"\x02{len(marks) - 1}\x02"

    # Bold first, so `**x**` is not read as two italics.
    text = re.sub(r"\*\*([^*]+)\*\*", take_bold, text)
    text = re.sub(r"\*([^*\n]+)\*", take_italic, text)

    text = esc(text)

    for i, m in enumerate(marks):
        text = text.replace(esc(f"\x02{i}\x02"), m).replace(f"\x02{i}\x02", m)
    for i, l in enumerate(links):
        text = text.replace(esc(f"\x01{i}\x01"), l).replace(f"\x01{i}\x01", l)
    for i, c in enumerate(codes):
        raw = "`" + c.replace("`", "\u2018") + "`"
        text = text.replace(esc(f"\x00{i}\x00"), raw).replace(f"\x00{i}\x00", raw)
    return text


def cells(row: str) -> list[str]:
    """Split one Markdown table row into its cells."""
    return [c.strip() for c in row.strip().strip("|").split("|")]


def convert(md: str, title: str) -> str:
    out: list[str] = []
    out.append("// Generated by scripts/md2typ.py — edit the Markdown source, not this file.\n")
    out.append(f'#set document(title: "{title}")\n')
    out.append('#set page(paper: "a4", margin: (x: 2.2cm, y: 2.6cm), numbering: "1")\n')
    out.append('#set text(font: ("Libertinus Serif", "Liberation Serif", "DejaVu Serif"), size: 10.5pt)\n')
    out.append("#set par(justify: true, leading: 0.7em)\n")
    out.append('#set heading(numbering: "1.1.")\n')
    out.append('#show link: set text(fill: rgb("#1a4d8f"))\n')
    out.append("#show raw.where(block: true): it => block(\n")
    out.append("  fill: luma(245), inset: (x: 9pt, y: 7pt), radius: 3pt, width: 100%, it,\n)\n")
    out.append("#show heading.where(level: 1): it => { pagebreak(weak: true); v(0.4em); it }\n\n")
    out.append(f"#align(center)[#text(size: 20pt, weight: 700)[{esc(title)}]]\n")
    out.append("#v(1.2em)\n#outline(depth: 2)\n#pagebreak()\n\n")

    lines = md.split("\n")
    i = 0
    seen_h1 = [False]
    para: list[str] = []

    def flush() -> None:
        if para:
            out.append(inline(" ".join(para)) + "\n\n")
            para.clear()

    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):
            flush()
            out.append("```" + line[3:].strip() + "\n")
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                out.append(lines[i] + "\n")
                i += 1
            out.append("```\n\n")
            i += 1
            continue

        # An HTML comment block (the licence header) is not content.
        if line.startswith("<!--"):
            flush()
            while i < len(lines) and "-->" not in lines[i]:
                i += 1
            i += 1
            continue

        if not line.strip():
            flush()
            i += 1
            continue

        if line.startswith("#"):
            flush()
            level = len(line) - len(line.lstrip("#"))
            # The document's own H1 is already the cover title; printing it again
            # would give the PDF two titles and an empty first section.
            if level == 1 and not seen_h1[0]:
                seen_h1[0] = True
                i += 1
                continue
            out.append("=" * level + " " + inline(line[level:].strip()) + "\n\n")
            i += 1
            continue

        if re.match(r"^\s*(---|===)\s*$", line):
            flush()
            out.append("#line(length: 100%, stroke: 0.4pt + luma(180))\n\n")
            i += 1
            continue

        # A table: a header row, a separator of dashes, then the body.
        if line.lstrip().startswith("|") and i + 1 < len(lines) and re.match(
            r"^\s*\|[\s:|-]+\|\s*$", lines[i + 1]
        ):
            flush()
            head = cells(line)
            i += 2
            body: list[list[str]] = []
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                body.append(cells(lines[i]))
                i += 1
            cols = len(head)
            out.append(f"#table(\n  columns: {cols}, stroke: 0.4pt + luma(200), inset: 5pt,\n")
            out.append("  ".join([]) + "  table.header(" + ", ".join(
                f"[{inline(h)}]" for h in head) + "),\n")
            for row in body:
                row = (row + [""] * cols)[:cols]
                out.append("  " + ", ".join(f"[{inline(c)}]" for c in row) + ",\n")
            out.append(")\n\n")
            continue

        if line.lstrip().startswith(">"):
            flush()
            quote: list[str] = []
            while i < len(lines) and lines[i].lstrip().startswith(">"):
                quote.append(lines[i].lstrip()[1:].strip())
                i += 1
            body = " ".join(q for q in quote if q)
            out.append(
                "#block(fill: luma(248), inset: 8pt, radius: 3pt, width: 100%)[" +
                inline(body) + "]\n\n"
            )
            continue

        m = re.match(r"^(\s*)([-*]|\d+\.)\s+(.*)$", line)
        if m:
            flush()
            indent, marker, rest = m.group(1), m.group(2), m.group(3)
            bullet = "+" if marker[0].isdigit() else "-"
            # Continuation lines of the same item are indented under it.
            i += 1
            while i < len(lines) and lines[i].strip() and not re.match(
                r"^(\s*)([-*]|\d+\.)\s+", lines[i]
            ) and not lines[i].startswith("#") and lines[i].startswith(" "):
                rest += " " + lines[i].strip()
                i += 1
            out.append(f"{indent}{bullet} " + inline(rest) + "\n")
            if i >= len(lines) or not lines[i].strip():
                out.append("\n")
            continue

        para.append(line.strip())
        i += 1

    flush()
    return "".join(out)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: md2typ.py <input.md> <output.typ>", file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    text = open(src, encoding="utf-8").read()
    title = "Document"
    for line in text.split("\n"):
        if line.startswith("# "):
            title = line[2:].strip()
            # `NAME.md — the real title` reads better in a PDF as just the real title.
            if "—" in title:
                title = title.split("—", 1)[1].strip()
                title = title[:1].upper() + title[1:]
            break
    open(dst, "w", encoding="utf-8").write(convert(text, title))
    print(f"md2typ: wrote {dst} ({title})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
