// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Runtime helper functions for native Rust code generated by `generation.rs`.
//!
//! The bytecode interpreter implements these operations as opcodes that read
//! parameters from the bytecode stream and manipulate the stack.  Generated
//! native code calls these wrapper functions directly with explicit arguments.
//!
//! **Interpreter safety:** This module is purely additive — it does not modify
//! any interpreter code path.  It only re-exposes `Stores` methods with the
//! signatures that generated code expects.
//!
//! `dead_code` is suppressed because every public item here is part of the
//! generated-code ABI — callers are emitted by `generation.rs`, not by the
//! interpreter or test suite directly.
#![allow(dead_code)]
#![allow(non_snake_case)]

use crate::database::{ShowDb, Stores};
use crate::keys::{Content, DbRef, Key, Str};
use crate::ops;
use crate::tree;

/// Convert a DbRef to a loft_ffi::LoftRef for passing to native C-ABI functions.
/// Both types have identical layout (u16 + u32 + u32).
#[must_use]
pub fn to_loft_ref(db: DbRef) -> loft_ffi::LoftRef {
    loft_ffi::LoftRef {
        store_nr: db.store_nr,
        rec: db.rec,
        pos: db.pos,
    }
}
use crate::vector;
use std::cell::RefCell;
#[cfg(not(feature = "wasm"))]
use std::fs::{File, OpenOptions};
#[cfg(not(feature = "wasm"))]
use std::io::{Read, Seek, SeekFrom, Write as _};
#[cfg(not(feature = "wasm"))]
use std::time::{SystemTime, UNIX_EPOCH};

/// Allocate a database root record for the given type.
/// The generated code calls this as `OpDatabase(stores, var, tp)` where `var` is
/// passed by value (`DbRef`).  The function allocates into the store referenced by
/// `db`, then returns the updated `DbRef`.
/// Bytecode equivalent: `OpDatabase` in `src/state/io.rs:319`.
pub fn OpDatabase(stores: &mut Stores, mut db: DbRef, db_tp: i32) -> DbRef {
    let db_tp = db_tp as u16;
    let size = stores.size(db_tp);
    if db.store_nr == u16::MAX {
        // Null sentinel (no real store yet) — allocate a fresh one.
        db = stores.null();
    }
    stores.clear(&db);
    let r = stores.claim(&db, u32::from(size));
    stores.store_mut(&r).set_u32_raw(r.rec, 4, u32::from(db_tp));
    stores.set_default_value(db_tp, &r);
    db.store_nr = r.store_nr;
    db.rec = 1;
    db.pos = 8;
    db
}

/// Create a new record element inside a vector/sorted/index collection.
/// Returns a `DbRef` pointing to the new element with default field values.
/// Bytecode equivalent: `OpNewRecord` in `src/state/io.rs:336`.
pub fn OpNewRecord(stores: &mut Stores, data: DbRef, parent_tp: i32, fld: i32) -> DbRef {
    let parent_tp = parent_tp as u16;
    let fld = fld as u16;
    let new_value = stores.record_new(&data, parent_tp, fld);
    stores.set_default_value(
        if fld == u16::MAX {
            stores.content(parent_tp)
        } else {
            stores.content(stores.field_type(parent_tp, fld))
        },
        &new_value,
    );
    new_value
}

/// Finalize a record after its fields have been assigned.
/// For sorted/index collections this inserts the record at the correct position.
/// Bytecode equivalent: `OpFinishRecord` in `src/state/io.rs:772`.
pub fn OpFinishRecord(stores: &mut Stores, data: DbRef, record: DbRef, parent_tp: i32, fld: i32) {
    stores.record_finish(&data, &record, parent_tp as u16, fld as u16);
}

/// Free a database reference.  Closes any associated file handle first.
/// Bytecode equivalent: `OpFreeRef` in `src/state/io.rs:262`.
/// The `name` argument is the loft variable name (e.g. `"var_p"`); it appears in
/// `LOFT_STORE_LOG` output for diagnosing LIFO store-free order violations.
pub fn OpFreeRef(stores: &mut Stores, db: DbRef, name: &str) {
    if db.store_nr == u16::MAX {
        return;
    }
    if (db.store_nr as usize) >= stores.allocations.len() {
        return;
    }
    // Reference counting: only close file handles when this is the last ref.
    #[cfg(not(feature = "wasm"))]
    if !stores.allocations[db.store_nr as usize].free
        && stores.allocations[db.store_nr as usize].ref_count <= 1
        && db.rec != 0
        && let Some(&file_type) = stores.names.get("File")
    {
        let stored_type = stores.store(&db).get_u32_raw(db.rec, 4) as u16;
        if stored_type == file_type {
            let file_ref = stores.store(&db).get_i32_raw(db.rec, db.pos + 28);
            if file_ref != i32::MIN && (file_ref as usize) < stores.files.len() {
                stores.files[file_ref as usize] = None;
            }
        }
    }
    stores.free_named(&db, name);
}

/// Format a database record as text and append it to the output string.
/// Bytecode equivalent: `OpFormatDatabase` in `src/state/io.rs:278`.
pub fn OpFormatDatabase(
    stores: &mut Stores,
    output: &mut String,
    record: DbRef,
    db_tp: i32,
    db_format: i32,
) {
    let mut s = String::new();
    ShowDb {
        stores,
        store: record.store_nr,
        rec: record.rec,
        pos: record.pos,
        known_type: db_tp as u16,
        pretty: db_format & 1 > 0,
        json: db_format & 2 > 0,
    }
    .write(&mut s, 0);
    output.push_str(&s);
}

/// Look up a record in a collection by key values.
/// Bytecode equivalent: `OpGetRecord` in `src/state/io.rs:353`.
pub fn OpGetRecord(
    stores: &mut Stores,
    data: DbRef,
    db_tp: i32,
    key: &[crate::keys::Content],
) -> DbRef {
    if data.rec == 0 {
        DbRef {
            store_nr: data.store_nr,
            rec: 0,
            pos: 0,
        }
    } else {
        stores.find(&data, db_tp as u16, key)
    }
}

/// Extract a substring from a text value.
///
/// `from` and `till` are **byte** indices into the UTF-8 string (matching the
/// bytecode interpreter in `src/state/text.rs`):
/// - `from` is snapped *backward* to the start of its containing character if
///   it points into the middle of a multi-byte sequence.
/// - `till` is snapped *forward* past continuation bytes so it lands on the
///   next character boundary.
/// - A negative `till` counts from the end of the string (`till += len`).
///
/// Bytecode equivalent: `State::get_text_sub` in `src/state/text.rs`.
#[must_use]
pub fn OpGetTextSub(text: &str, from: i32, till: i32) -> &str {
    let bytes = text.as_bytes();
    let len = bytes.len() as i32;
    if from < 0 || from >= len {
        return "";
    }
    // Snap `from` backward to the start of the current character.
    let mut f = from as usize;
    while f > 0 && bytes[f] & 0xC0 == 0x80 {
        f -= 1;
    }
    // Resolve negative `till` to a forward byte offset.
    let t_raw = if till < 0 { len + till } else { till };
    if t_raw <= f as i32 {
        return "";
    }
    // Clamp to string length.
    let mut t = t_raw.min(len) as usize;
    // Snap `till` forward past any continuation bytes so it lands on a
    // character boundary (mirrors the interpreter behaviour).
    while t < bytes.len() && bytes[t] & 0xC0 == 0x80 {
        t += 1;
    }
    &text[f..t]
}

/// Return the byte size of a database record's type.
/// Bytecode equivalent: `OpSizeofRef` in `src/state/io.rs:290`.
#[must_use]
pub fn OpSizeofRef(stores: &Stores, db: DbRef) -> i32 {
    if db.rec == 0 {
        0
    } else {
        let tp = stores.store(&db).get_u32_raw(db.rec, 4) as u16;
        i32::from(stores.size(tp))
    }
}

/// Parse a text representation into a database record.
/// Bytecode equivalent: `State::db_from_text` in `src/state/io.rs:780`.
#[must_use]
pub fn db_from_text(stores: &mut Stores, val: &str, db_tp: u16) -> DbRef {
    let db = stores.database(8);
    let into = DbRef {
        store_nr: db.store_nr,
        rec: db.rec,
        pos: 8,
    };
    stores.set_default_value(db_tp, &into);
    stores.last_parse_errors.clear();
    if let Some(err) = stores.parse(val, db_tp, &into) {
        stores.last_parse_errors.push(err);
    }
    into
}

/// Return the parse errors from the last `Type.parse()` call as a single
/// newline-separated string.  Called by the `#errors` accessor.
pub fn i_parse_errors(stores: &mut Stores) -> Str {
    let msg = stores.last_parse_errors.join("\n");
    stores.last_parse_errors.clear();
    stores.scratch.clear();
    stores.scratch.push(msg);
    Str::new(&stores.scratch[0])
}

/// Push a constraint-check error to the parse error list.
pub fn i_parse_error_push(stores: &mut Stores, msg: &str) {
    stores.last_parse_errors.push(msg.to_owned());
}

/// Return the JSON parse / schema-walk errors from the last `json_parse()`
/// or `Struct.parse(JsonValue)` call as a single `|`-separated string.
/// Mirrors the interpreter's `n_json_errors` (`src/native.rs`) which does
/// NOT clear the buffer — errors persist across `json_errors()` reads
/// until the next successful parse implicitly clears them.
pub fn i_json_errors(stores: &mut Stores) -> Str {
    let msg = stores.last_json_errors.join("|");
    stores.scratch.clear();
    stores.scratch.push(msg);
    Str::new(&stores.scratch[0])
}

/// Deep-copy a database record: copies the raw bytes and duplicates
/// all owned sub-structures (text fields, vectors, etc.).
/// Bytecode equivalent: `State::copy_record` in `src/state/io.rs:697`.
pub fn OpCopyRecord(stores: &mut Stores, data: DbRef, to: DbRef, tp: i32) {
    // P171: mirror `state/io.rs::copy_record`'s tag handling and
    // cleanup.  The bytecode form masks the high bit of `tp` before
    // indexing into `stores.types` (Issue #120 / P143 use 0x8000 as
    // "free source after copy"); native codegen was missing both the
    // mask and the free, so any caller that set the flag — e.g.
    // `copy_ref` on a struct-returning call's result — panicked at
    // `Types::size()` with an out-of-bounds index.  Also missing:
    // `remove_claims` before the overwrite, which the bytecode form
    // uses to free the destination's nested vectors/strings so a
    // reassignment doesn't double-free on scope exit.
    let raw_tp = tp as u16;
    let free_source = raw_tp & 0x8000 != 0;
    let tp = raw_tp & 0x7FFF;
    let size = u32::from(stores.size(tp));
    stores.remove_claims(&to, tp);
    stores.copy_block(&data, &to, size);
    stores.copy_claims(&data, &to, tp);
    if free_source
        && data.store_nr != to.store_nr
        && data.store_nr != 0
        && !stores.allocations[data.store_nr as usize].free
        && !stores.allocations[data.store_nr as usize].locked
    {
        stores.free(&data);
    }
}

/// Sort a vector in-place using the element type's natural ordering.
/// Bytecode equivalent: `sort_vector` in `src/fill.rs:1835`.
pub fn OpSortVector(stores: &mut Stores, data: DbRef, db_tp: i32) {
    let db_tp = db_tp as u16;
    let elem_size = stores.size(db_tp);
    let is_float = db_tp == 2 || db_tp == 3;
    vector::sort_vector(&data, elem_size, is_float, &mut stores.allocations);
}

/// Insert a new default-valued element at `index` in a vector, shifting later elements right.
/// Returns a `DbRef` pointing to the newly inserted element.
/// Bytecode equivalent: `State::insert_vector` in `src/state/io.rs:819`.
pub fn OpInsertVector(
    stores: &mut Stores,
    data: DbRef,
    size: i32,
    index: i32,
    db_tp: i32,
) -> DbRef {
    let new_value = vector::insert_vector(&data, size as u32, i64::from(index), &mut stores.allocations);
    stores.set_default_value(db_tp as u16, &new_value);
    new_value
}

/// Return the UTF-8 byte length of a character (encoded as `i32` in loft).
/// Returns 0 for the null character sentinel.
/// Bytecode equivalent: `State::length_character` in `src/state/text.rs:54`.
#[must_use]
pub fn OpLengthCharacter(_stores: &mut Stores, c: i32) -> i32 {
    let ch = ops::to_char(c);
    if ch == '\0' {
        0
    } else {
        i32::try_from(ch.len_utf8()).unwrap_or(0)
    }
}

/// Pack a (current-position, finish) pair into a single i64 iterator state.
/// High 32 bits = finish; low 32 bits = cur.
/// `finish == u32::MAX` signals that iteration is complete.
fn pack_iter(cur: u32, finish: u32) -> i64 {
    ((u64::from(finish) << 32) | u64::from(cur)).cast_signed()
}

/// Build a minimal `DbRef` pointing at record `rec` with field offset `pos`.
fn iter_ref(data: &DbRef, rec: u32, pos: u16) -> DbRef {
    DbRef {
        store_nr: data.store_nr,
        rec,
        pos: u32::from(pos),
    }
}

/// Initialize a sorted/index iterator state and return it as a packed `i64`.
///
/// `on` encodes collection type and flags:
/// - bits 0–5: collection type (1 = red-black tree / index, 2 = sorted vector)
/// - bit 6: reverse iteration
/// - bit 7: inclusive end (if clear, end is exclusive)
///
/// `arg` is the element size in bytes (sorted) or the tree-fields offset (index).
/// `keys` describes the key fields in the collection type.
/// `from` / `till` are the from/till key values; empty slices mean start/end of collection.
///
/// The returned `i64` is consumed by [`OpStep`].
/// Bytecode equivalent: `State::iterate` in `src/state/io.rs`.
#[must_use]
pub fn OpIterate(
    stores: &Stores,
    data: DbRef,
    on: i32,
    arg: i32,
    keys: &[Key],
    from: &[Content],
    till: &[Content],
) -> i64 {
    if data.rec == 0 {
        return pack_iter(u32::MAX, u32::MAX);
    }
    let reverse = (on & 64) != 0;
    let ex = (on & 128) == 0;
    let all = &stores.allocations;
    match on & 63 {
        2 => {
            // sorted vector: arg = element size in bytes
            let size = arg as u16;
            if reverse {
                let s = vector::sorted_find(&data, ex, size, all, keys, till).0 + u32::from(!ex);
                let f = vector::sorted_find(&data, ex, size, all, keys, from).0 + 1;
                pack_iter(s, f)
            } else {
                let s = vector::sorted_find(&data, true, size, all, keys, from).0;
                let start = if s == 0 { u32::MAX } else { s - 1 };
                let (t, cmp) = vector::sorted_find(&data, ex, size, all, keys, till);
                let finish = if ex || cmp { t } else { t + 1 };
                pack_iter(start, finish)
            }
        }
        1 => {
            // red-black tree / index: arg = fields offset
            let fields = arg as u16;
            let store = crate::keys::store(&data, all);
            if reverse {
                // start = one past last element, finish = one before first.
                let till_node = tree::find(&data, true, fields, all, keys, till);
                let start = if ex {
                    tree::next(store, &iter_ref(&data, till_node, fields))
                } else {
                    let till_match = tree::find(&data, false, fields, all, keys, till);
                    tree::next(store, &iter_ref(&data, till_match, fields))
                };
                let finish = tree::find(&data, true, fields, all, keys, from);
                pack_iter(start, finish)
            } else {
                let start = tree::find(&data, true, fields, all, keys, from);
                let t = tree::find(&data, ex, fields, all, keys, till);
                let finish = if ex {
                    t
                } else {
                    tree::previous(store, &iter_ref(&data, t, fields))
                };
                pack_iter(start, finish)
            }
        }
        3 => {
            // C60 piece 3: Ordered iteration — `data` points at a
            // header record whose offset-4 word is the u32-stride
            // rec-nr vector rec-nr.  Unbounded form (from/till empty)
            // uses the "not started" sentinel recognised by
            // `vector_next` (i32::MAX = 0x7FFF_FFFF), NOT u32::MAX.
            if from.is_empty() && till.is_empty() {
                pack_iter(i32::MAX as u32, 0)
            } else if reverse {
                let s = vector::ordered_find(&data, ex, all, keys, till).0 + u32::from(!ex);
                let f = vector::ordered_find(&data, ex, all, keys, from).0 + 1;
                pack_iter(s, f)
            } else {
                let s = vector::ordered_find(&data, true, all, keys, from).0;
                let start = if s == 0 { u32::MAX } else { s - 1 };
                let (t, cmp) = vector::ordered_find(&data, ex, all, keys, till);
                let finish = if ex || cmp { t } else { t + 1 };
                pack_iter(start, finish)
            }
        }
        _ => pack_iter(u32::MAX, u32::MAX),
    }
}

/// Advance the iterator to the next element and return a `DbRef` pointing to it.
/// Returns a `DbRef` with `rec == 0` when iteration is complete.
///
/// `iter` is the mutable `i64` state returned by [`OpIterate`]; it is updated in place.
/// `on` and `arg` must match the corresponding `OpIterate` call.
///
/// Bytecode equivalent: `State::step` in `src/state/io.rs`.
pub fn OpStep(stores: &Stores, iter: &mut i64, data: DbRef, on: i32, arg: i32) -> DbRef {
    let mut cur = (*iter as u64) as u32;
    let mut finish = ((*iter as u64) >> 32) as u32;

    if data.rec == 0 || finish == u32::MAX {
        return stores.element_reference(&data, i32::MAX);
    }

    let reverse = (on & 64) != 0;
    let all = &stores.allocations;

    let result = match on & 63 {
        2 => {
            // sorted vector: arg = element size
            let mut pos = if cur == u32::MAX {
                i32::MAX
            } else {
                cur as i32
            };
            if reverse {
                vector::vector_step_rev(&data, &mut pos, all);
                if pos == i32::MAX {
                    finish = u32::MAX;
                }
            } else {
                vector::vector_step(&data, &mut pos, all);
                if pos as u32 >= finish {
                    pos = i32::MAX;
                }
            }
            cur = pos as u32;
            let byte_pos = if pos == i32::MAX {
                i32::MAX
            } else {
                8 + pos * arg
            };
            if pos == i32::MAX {
                finish = u32::MAX;
            }
            stores.element_reference(&data, byte_pos)
        }
        1 => {
            // red-black tree / index: arg = fields offset
            let fields = arg as u16;
            let store = crate::keys::store(&data, all);
            let next_rec = if cur == 0 {
                if reverse {
                    tree::last(&data, fields, all).rec
                } else {
                    tree::first(&data, fields, all).rec
                }
            } else if reverse {
                tree::previous(store, &iter_ref(&data, cur, fields))
            } else {
                tree::next(store, &iter_ref(&data, cur, fields))
            };
            if next_rec == finish {
                finish = u32::MAX;
            }
            cur = next_rec;
            DbRef {
                store_nr: data.store_nr,
                rec: next_rec,
                pos: 8,
            }
        }
        3 => {
            // C60 piece 3: Ordered iteration over u32-stride rec-nr
            // vector.  Mirrors src/state/io.rs step() on=3 arm.
            let mut pos = cur as i32;
            vector::vector_next(&data, &mut pos, 4, all);
            let store = crate::keys::store(&data, all);
            let vector = store.get_u32_raw(data.rec, data.pos);
            let rec = if pos == i32::MAX {
                0
            } else {
                store.get_u32_raw(vector, pos as u32)
            };
            cur = pos as u32;
            DbRef {
                store_nr: data.store_nr,
                rec,
                pos: 8,
            }
        }
        _ => stores.element_reference(&data, i32::MAX),
    };

    *iter = pack_iter(cur, finish);
    result
}

/// Read the entire contents of a file into `content`, replacing its previous value.
/// If the file cannot be opened or read, `content` is cleared.
/// Bytecode equivalent: `State::get_file_text` in `src/state/io.rs`.
#[cfg(not(feature = "wasm"))]
pub fn OpGetFileText(stores: &mut Stores, file: DbRef, content: &mut String) {
    if file.rec == 0 {
        return;
    }
    let file_path = {
        let store = stores.store(&file);
        store
            .get_str(store.get_u32_raw(file.rec, file.pos + 24))
            .to_owned()
    };
    content.clear();
    if let Ok(mut f) = File::open(&file_path)
        && f.read_to_string(content).is_err()
    {
        content.clear();
    }
}

/// WASM stub: file I/O not available; clears content.
#[cfg(feature = "wasm")]
pub fn OpGetFileText(_stores: &mut Stores, _file: DbRef, content: &mut String) {
    content.clear();
}

/// Seek to `pos` bytes from the start of the file.
/// If the file handle is not yet open, stores `pos` in `#next` so the first
/// read/write applies the seek after opening.
/// Bytecode equivalent: `State::seek_file` in `src/state/io.rs`.
#[cfg(not(feature = "wasm"))]
pub fn OpSeekFile(stores: &mut Stores, file: DbRef, pos: i64) {
    if file.rec == 0 {
        return;
    }
    let file_ref = stores.store(&file).get_i32_raw(file.rec, file.pos + 28);
    if file_ref == i32::MIN {
        stores
            .store_mut(&file)
            .set_long(file.rec, file.pos + 16, pos);
    } else if let Some(f) = &mut stores.files[file_ref as usize]
        && let Err(e) = f.seek(SeekFrom::Start(pos as u64))
    {
        eprintln!("file seek error: {e}");
    }
}

/// WASM stub: file I/O not available.
#[cfg(feature = "wasm")]
pub fn OpSeekFile(_stores: &mut Stores, _file: DbRef, _pos: i64) {}

/// Return the byte size of the file, or `i64::MIN` if the size cannot be determined.
/// Bytecode equivalent: `State::size_file` in `src/state/io.rs`.
#[must_use]
#[cfg(not(feature = "wasm"))]
pub fn OpSizeFile(stores: &Stores, file: DbRef) -> i64 {
    if file.rec == 0 {
        return i64::MIN;
    }
    let file_path = {
        let store = stores.store(&file);
        store
            .get_str(store.get_u32_raw(file.rec, file.pos + 24))
            .to_owned()
    };
    if let Ok(meta) = std::fs::metadata(&file_path) {
        meta.len().cast_signed()
    } else {
        i64::MIN
    }
}

/// WASM stub: file I/O not available; always returns `i64::MIN`.
#[must_use]
#[cfg(feature = "wasm")]
pub fn OpSizeFile(_stores: &Stores, _file: DbRef) -> i64 {
    i64::MIN
}

/// Truncate (or extend) the file to `size` bytes.  Closes any open handle first.
/// Returns `true` on success, `false` on failure.
/// Bytecode equivalent: `State::truncate_file` in `src/state/io.rs`.
#[cfg(not(feature = "wasm"))]
pub fn OpTruncateFile(stores: &mut Stores, file: DbRef, size: i64) -> bool {
    if file.rec == 0 {
        return false;
    }
    let file_path = {
        let store = stores.store(&file);
        store
            .get_str(store.get_u32_raw(file.rec, file.pos + 24))
            .to_owned()
    };
    // Close any open handle so resize starts from a clean state.
    let file_ref = stores.store(&file).get_i32_raw(file.rec, file.pos + 28);
    if file_ref != i32::MIN && (file_ref as usize) < stores.files.len() {
        stores.files[file_ref as usize] = None;
        stores
            .store_mut(&file)
            .set_i32_raw(file.rec, file.pos + 28, i32::MIN);
        stores
            .store_mut(&file)
            .set_long(file.rec, file.pos + 8, i64::MIN);
        stores
            .store_mut(&file)
            .set_long(file.rec, file.pos + 16, i64::MIN);
    }
    OpenOptions::new()
        .write(true)
        .open(&file_path)
        .and_then(|f| f.set_len(size as u64))
        .is_ok()
}

/// WASM stub: file I/O not available; always returns `false`.
#[cfg(feature = "wasm")]
pub fn OpTruncateFile(_stores: &mut Stores, _file: DbRef, _size: i64) -> bool {
    false
}

// ─── File I/O ─────────────────────────────────────────────────────────────────

/// Open (or reuse) a file handle for writing.  Returns the index into
/// `stores.files`, or `i32::MIN` on error.
#[cfg(not(feature = "wasm"))]
fn file_handle_write(stores: &mut Stores, file: &DbRef) -> i32 {
    let f_nr = stores.files.len() as i32;
    let file_ref = stores.store(file).get_i32_raw(file.rec, file.pos + 28);
    if file_ref != i32::MIN {
        return file_ref;
    }
    let (file_name, format) = {
        let store = stores.store(file);
        (
            store
                .get_str(store.get_u32_raw(file.rec, file.pos + 24))
                .to_owned(),
            store.get_byte(file.rec, file.pos + 32, 0),
        )
    };
    match File::create(&file_name) {
        Ok(f) => {
            stores
                .store_mut(file)
                .set_i32_raw(file.rec, file.pos + 28, f_nr);
            // If the file was NotExists, mark it as TextFile now that it exists.
            if format == 5 {
                stores
                    .store_mut(file)
                    .set_byte(file.rec, file.pos + 32, 0, 1);
            }
            stores.files.push(Some(f));
            f_nr
        }
        Err(e) => {
            eprintln!("file create error for {file_name:?}: {e}");
            i32::MIN
        }
    }
}

/// Open (or reuse) a file handle for reading, seeking to `initial_pos`.
/// Returns the index into `stores.files`, or `i32::MIN` on error.
#[cfg(not(feature = "wasm"))]
fn file_handle_read(stores: &mut Stores, file: &DbRef, initial_pos: i64) -> i32 {
    let f_nr = stores.files.len() as i32;
    let file_ref = stores.store(file).get_i32_raw(file.rec, file.pos + 28);
    if file_ref != i32::MIN {
        return file_ref;
    }
    let file_name = {
        let store = stores.store(file);
        store
            .get_str(store.get_u32_raw(file.rec, file.pos + 24))
            .to_owned()
    };
    match OpenOptions::new().read(true).open(&file_name) {
        Ok(mut f) => {
            if initial_pos > 0 {
                let _ = f.seek(SeekFrom::Start(initial_pos as u64));
            }
            stores
                .store_mut(file)
                .set_i32_raw(file.rec, file.pos + 28, f_nr);
            stores.files.push(Some(f));
            f_nr
        }
        Err(e) => {
            eprintln!("file open error for {file_name:?}: {e}");
            i32::MIN
        }
    }
}

/// Trait for types that can be written to / read from a loft binary or text file.
///
/// The `db_tp` parameter is the loft type index stored in `stores.types`; it
/// controls how many bytes are used and the interpretation (integer vs byte vs
/// short vs text, etc.).
pub trait FileVal {
    /// Serialise `self` into bytes that will be appended to the file.
    fn file_to_bytes(&self, stores: &Stores, db_tp: i32, little_endian: bool) -> Vec<u8>;
    /// Deserialise `bytes` (already read from the file) into `self`.
    /// Receives `&mut Stores` so that collection types (e.g. `vector<T>`) can append elements.
    fn file_from_bytes(
        &mut self,
        stores: &mut Stores,
        db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    );
}

impl FileVal for i32 {
    fn file_to_bytes(&self, stores: &Stores, db_tp: i32, little_endian: bool) -> Vec<u8> {
        let mut out = Vec::new();
        match db_tp {
            0 | 6 => {
                // integer | character — 4 bytes
                let b = if little_endian {
                    self.to_le_bytes()
                } else {
                    self.to_be_bytes()
                };
                out.extend_from_slice(&b);
            }
            4 => out.push(*self as u8), // boolean — 1 byte
            _ => match &stores.types[db_tp as usize].parts {
                crate::database::Parts::Byte(_, _) => out.push(*self as u8),
                crate::database::Parts::Short(_, _) => {
                    let v = *self as i16;
                    let b = if little_endian {
                        v.to_le_bytes()
                    } else {
                        v.to_be_bytes()
                    };
                    out.extend_from_slice(&b);
                }
                _ => {
                    let b = if little_endian {
                        self.to_le_bytes()
                    } else {
                        self.to_be_bytes()
                    };
                    out.extend_from_slice(&b);
                }
            },
        }
        out
    }

    fn file_from_bytes(
        &mut self,
        stores: &mut Stores,
        db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        match db_tp {
            0 | 6 => {
                if bytes.len() >= 4 {
                    *self = if little_endian {
                        i32::from_le_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                    } else {
                        i32::from_be_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                    };
                }
            }
            4 => {
                if let Some(&b) = bytes.first() {
                    *self = i32::from(b);
                }
            }
            _ => match &stores.types[db_tp as usize].parts {
                crate::database::Parts::Byte(_, _) => {
                    if let Some(&b) = bytes.first() {
                        *self = i32::from(b);
                    }
                }
                crate::database::Parts::Short(_, _) => {
                    if bytes.len() >= 2 {
                        let v = if little_endian {
                            i16::from_le_bytes(bytes[..2].try_into().unwrap_or([0; 2]))
                        } else {
                            i16::from_be_bytes(bytes[..2].try_into().unwrap_or([0; 2]))
                        };
                        *self = i32::from(v);
                    }
                }
                _ => {
                    if bytes.len() >= 4 {
                        *self = if little_endian {
                            i32::from_le_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                        } else {
                            i32::from_be_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                        };
                    }
                }
            },
        }
    }
}

impl FileVal for i64 {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, little_endian: bool) -> Vec<u8> {
        if little_endian {
            self.to_le_bytes().to_vec()
        } else {
            self.to_be_bytes().to_vec()
        }
    }
    fn file_from_bytes(
        &mut self,
        _stores: &mut Stores,
        _db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        if bytes.len() >= 8 {
            *self = if little_endian {
                i64::from_le_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            } else {
                i64::from_be_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            };
        }
    }
}

impl FileVal for f32 {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, little_endian: bool) -> Vec<u8> {
        if little_endian {
            self.to_le_bytes().to_vec()
        } else {
            self.to_be_bytes().to_vec()
        }
    }
    fn file_from_bytes(
        &mut self,
        _stores: &mut Stores,
        _db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        if bytes.len() >= 4 {
            *self = if little_endian {
                f32::from_le_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
            } else {
                f32::from_be_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
            };
        }
    }
}

impl FileVal for f64 {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, little_endian: bool) -> Vec<u8> {
        if little_endian {
            self.to_le_bytes().to_vec()
        } else {
            self.to_be_bytes().to_vec()
        }
    }
    fn file_from_bytes(
        &mut self,
        _stores: &mut Stores,
        _db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        if bytes.len() >= 8 {
            *self = if little_endian {
                f64::from_le_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            } else {
                f64::from_be_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            };
        }
    }
}

impl FileVal for String {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, _little_endian: bool) -> Vec<u8> {
        self.as_bytes().to_vec()
    }
    fn file_from_bytes(
        &mut self,
        _stores: &mut Stores,
        _db_tp: i32,
        _little_endian: bool,
        bytes: &[u8],
    ) {
        *self = String::from_utf8_lossy(bytes).into_owned();
    }
}

impl FileVal for DbRef {
    /// Serialise a vector (or struct/simple) `DbRef` into bytes for binary file output.
    ///
    /// For `Parts::Vector(elem_tp)` the method iterates every element and delegates to
    /// `Stores::read_data`; for all other types it calls `read_data` on `self` directly.
    fn file_to_bytes(&self, stores: &Stores, db_tp: i32, little_endian: bool) -> Vec<u8> {
        use crate::database::Parts;
        let mut data = Vec::new();
        if let Some(tp_info) = stores.types.get(db_tp as usize) {
            if let Parts::Vector(elem_tp) = tp_info.parts {
                let store = &stores.allocations[self.store_nr as usize];
                let v_rec = store.get_u32_raw(self.rec, self.pos);
                if v_rec != 0 {
                    let length = store.get_u32_raw(v_rec, 4);
                    let elem_size = u32::from(stores.size(elem_tp));
                    for i in 0..length {
                        let elem = DbRef {
                            store_nr: self.store_nr,
                            rec: v_rec,
                            pos: 8 + elem_size * i,
                        };
                        stores.read_data(&elem, elem_tp, little_endian, &mut data);
                    }
                }
            } else {
                stores.read_data(self, db_tp as u16, little_endian, &mut data);
            }
        }
        data
    }

    fn file_from_bytes(
        &mut self,
        stores: &mut Stores,
        db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        use crate::database::Parts;
        if let Some(tp_info) = stores.types.get(db_tp as usize) {
            if let Parts::Vector(elem_tp) = tp_info.parts.clone() {
                let elem_size = u32::from(stores.size(elem_tp));
                if elem_size == 0 || bytes.is_empty() {
                    return;
                }
                // The generated code initialises the destination as a null sentinel
                // (store_nr=u16::MAX, rec=0).  Allocate a real store before the first
                // vector_append, which indexes stores[store_nr] and would panic on u16::MAX.
                if self.rec == 0 {
                    *self = stores.database(12);
                    // Zero-init the vector header slot so vector_append sees
                    // vec_rec=0 (no storage yet) instead of garbage memory.
                    stores.store_mut(self).set_u32_raw(self.rec, self.pos, 0);
                }
                let n_elems = bytes.len() / elem_size as usize;
                for i in 0..n_elems {
                    let slice = &bytes[i * elem_size as usize..(i + 1) * elem_size as usize];
                    let elem_ref =
                        crate::vector::vector_append(self, elem_size, &mut stores.allocations);
                    stores.write_data(&elem_ref, elem_tp, little_endian, slice);
                    crate::vector::vector_finish(self, &mut stores.allocations);
                }
            } else {
                stores.write_data(self, db_tp as u16, little_endian, bytes);
            }
        }
    }
}

/// Write a value to a loft `File` record.
/// Bytecode equivalent: `State::write_file` in `src/state/io.rs`.
#[cfg(not(feature = "wasm"))]
pub fn OpWriteFile<T: FileVal>(stores: &mut Stores, file: DbRef, val: &mut T, db_tp: i32) {
    if file.rec == 0 {
        return;
    }
    let format = stores.store(&file).get_byte(file.rec, file.pos + 32, 0);
    // format: 1=TextFile, 2=LittleEndian, 3=BigEndian, 5=NotExists
    if format != 1 && format != 2 && format != 3 && format != 5 {
        return;
    }
    let little_endian = format == 2;
    let file_ref = file_handle_write(stores, &file);
    if file_ref == i32::MIN {
        return;
    }
    // Track write position: set #index = where this write starts.
    let raw_next = stores.store(&file).get_long(file.rec, file.pos + 16);
    let next_pos = if raw_next == i64::MIN { 0 } else { raw_next };
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 8, next_pos);
    let data = val.file_to_bytes(stores, db_tp, little_endian);
    let written = data.len() as i64;
    if let Some(f) = stores
        .files
        .get_mut(file_ref as usize)
        .and_then(|x| x.as_mut())
        && let Err(e) = f.write_all(&data)
    {
        eprintln!("file write error: {e}");
    }
    // Update #next to reflect the end of this write.
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 16, next_pos + written);
}

/// WASM stub: file write not available.
#[cfg(feature = "wasm")]
pub fn OpWriteFile<T: FileVal>(_stores: &mut Stores, _file: DbRef, _val: &mut T, _db_tp: i32) {}

/// Read bytes from a loft `File` record into `val`.
/// Bytecode equivalent: `State::read_file` in `src/state/io.rs`.
#[cfg(not(feature = "wasm"))]
pub fn OpReadFile<T: FileVal>(
    stores: &mut Stores,
    file: DbRef,
    val: &mut T,
    bytes: i32,
    db_tp: i32,
) {
    if file.rec == 0 {
        return;
    }
    let format = stores.store(&file).get_byte(file.rec, file.pos + 32, 0);
    if format != 1 && format != 2 && format != 3 && format != 5 {
        return;
    }
    let little_endian = format == 2;
    // Track read position: #next holds the byte offset to read from.
    let raw_next = stores.store(&file).get_long(file.rec, file.pos + 16);
    let next_pos = if raw_next == i64::MIN { 0 } else { raw_next };
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 8, next_pos);
    let file_ref = file_handle_read(stores, &file, next_pos);
    if file_ref == i32::MIN {
        return;
    }
    let n = bytes.max(0) as usize;
    let mut buf = vec![0u8; n];
    let is_text = stores.is_text_type(db_tp as u16);
    let nread = if let Some(f) = stores
        .files
        .get_mut(file_ref as usize)
        .and_then(|x| x.as_mut())
    {
        if is_text {
            f.read(&mut buf).unwrap_or(0)
        } else if f.read_exact(&mut buf).is_ok() {
            n
        } else {
            0
        }
    } else {
        0
    };
    buf.truncate(nread);
    val.file_from_bytes(stores, db_tp, little_endian, &buf);
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 16, next_pos + nread as i64);
}

/// WASM stub: file read not available.
#[cfg(feature = "wasm")]
pub fn OpReadFile<T: FileVal>(
    _stores: &mut Stores,
    _file: DbRef,
    _val: &mut T,
    _bytes: i32,
    _db_tp: i32,
) {
}

/// Trait allowing `OpRemove` to work with both plain-vector (`i32` index) and
/// sorted/tree (`i64` packed iterator) state variables.
pub trait IterState {
    fn get_cur(&self) -> i32;
    fn set_cur(&mut self, n: i32);
    fn get_finish(&self) -> u32 {
        u32::MAX
    }
    fn set_finish(&mut self, _n: u32) {}
}

impl IterState for i32 {
    fn get_cur(&self) -> i32 {
        *self
    }
    fn set_cur(&mut self, n: i32) {
        *self = n;
    }
}

impl IterState for i64 {
    fn get_cur(&self) -> i32 {
        ((*self as u64) as u32).cast_signed()
    }
    fn set_cur(&mut self, n: i32) {
        let finish = (*self as u64) >> 32;
        *self = ((finish << 32) | u64::from(n as u32)).cast_signed();
    }
    fn get_finish(&self) -> u32 {
        ((*self as u64) >> 32) as u32
    }
    fn set_finish(&mut self, n: u32) {
        let cur = (*self as u64) as u32;
        *self = ((u64::from(n) << 32) | u64::from(cur)).cast_signed();
    }
}

/// Remove the element at the current iterator position and update the iterator
/// so the next step visits the correct successor.
///
/// - `on & 63 == 0`: plain vector — `arg` is the element type index; size is
///   looked up via `stores.get_type(arg as u16).size`.
/// - `on & 63 == 2`: sorted vector — `arg` is the element size in bytes directly.
///
/// Bytecode equivalent: `State::remove` in `src/state/io.rs`.
///
/// # Panics
/// Panics if `data.store_nr == u16::MAX` (coroutine `DbRef`) — the compiler is
/// expected to reject `e#remove` on generator iterators before this is reached.
pub fn OpRemove<S: IterState>(stores: &mut Stores, state: &mut S, data: DbRef, on: i32, arg: i32) {
    // Defense-in-depth: coroutine DbRefs (store_nr == u16::MAX) must not reach remove().
    // The compiler already rejects e#remove on generator iterators (CO1.5c / S24).
    assert!(
        data.store_nr != u16::MAX,
        "e#remove on coroutine DbRef — compiler check should have rejected this"
    );
    if data.store_nr == u16::MAX {
        return;
    }
    let cur = state.get_cur();
    let reverse = (on & 64) != 0;
    match on & 63 {
        0 => {
            // plain vector: arg is the element type index
            let elem_size = u32::from(stores.size(arg as u16));
            let n = if reverse { cur + 1 } else { cur - 1 };
            vector::remove_vector(&data, elem_size, i64::from(cur), &mut stores.allocations);
            state.set_cur(n);
        }
        1 => {
            // index (red-black tree): arg is the type index; fields offset derived from it
            let cur_u = cur as u32;
            if cur_u == u32::MAX {
                return;
            }
            let tp = arg as u16;
            let fields = stores.fields(tp);
            let cur_ref = iter_ref(&data, cur_u, fields);
            // Compute successor BEFORE removing so tree pointers are still intact.
            let n_after = {
                let store = crate::keys::store(&data, &stores.allocations);
                if reverse {
                    tree::previous(store, &cur_ref)
                } else {
                    tree::next(store, &cur_ref)
                }
            };
            stores.remove(&data, &cur_ref, tp);
            if n_after == 0 {
                // Removed the last element: signal end-of-iteration.
                state.set_finish(u32::MAX);
            } else {
                // Set cur to predecessor of n_after so the next OpStep visits n_after.
                let pred = {
                    let store = crate::keys::store(&data, &stores.allocations);
                    if reverse {
                        tree::next(store, &iter_ref(&data, n_after, fields))
                    } else {
                        tree::previous(store, &iter_ref(&data, n_after, fields))
                    }
                };
                state.set_cur(pred.cast_signed());
                // If n_after equals the finish boundary, signal end-of-iteration.
                if n_after == state.get_finish() {
                    state.set_finish(u32::MAX);
                }
            }
        }
        2 => {
            // sorted vector: arg is the element size in bytes
            if cur < 0 {
                return;
            }
            let n = if reverse { cur + 1 } else { cur - 1 };
            vector::remove_vector(&data, arg as u32, i64::from(cur), &mut stores.allocations);
            state.set_cur(n);
        }
        _ => {}
    }
}

/// Remove a record from a hash or index collection.
///
/// Bytecode equivalent: `State::hash_remove` in `src/state/io.rs`.
pub fn OpHashRemove(stores: &mut Stores, data: DbRef, rec: DbRef, tp: i32) {
    if rec.rec != 0 {
        stores.remove(&data, &rec, tp as u16);
    }
}

/// Append `count - 1` copies of the last element of `data`, expanding the vector.
///
/// Bytecode equivalent: `State::append_copy` in `src/state/io.rs`.
pub fn OpAppendCopy(stores: &mut Stores, data: DbRef, count: i32, tp: i32) {
    let ctp = stores.content(tp as u16);
    let size = u32::from(stores.size(ctp));
    let length = vector::length_vector(&data, &stores.allocations);
    // Read v_rec before resize; from points to the last existing element.
    let v_rec_before =
        crate::keys::store(&data, &stores.allocations).get_u32_raw(data.rec, data.pos);
    let from = DbRef {
        store_nr: data.store_nr,
        rec: v_rec_before,
        pos: 8 + (length * size - size),
    };
    let multiply = count as u32;
    // Resize to accommodate `multiply` additional elements.
    vector::vector_append(&data, size, &mut stores.allocations);
    stores.vector_set_size(&data, multiply, size);
    // Re-read v_rec in case the resize moved the record.
    let v_rec = crate::keys::store(&data, &stores.allocations).get_u32_raw(data.rec, data.pos);
    for i in 0..(multiply - 1) {
        let to = DbRef {
            store_nr: data.store_nr,
            rec: v_rec,
            pos: 8 + (length + i) * size,
        };
        stores.copy_block(&from, &to, size);
        stores.copy_claims(&data, &to, ctp);
    }
}

/// Wrappers for the `external` module emitted in generated native files.
/// Using these avoids `cfg(feature = "random")` in the generated code.
pub fn cr_rand_seed(seed: i64) {
    #[cfg(feature = "random")]
    crate::ops::rand_seed(seed);
    #[cfg(not(feature = "random"))]
    let _ = seed;
}
#[must_use]
pub fn cr_rand_int(lo: i32, hi: i32) -> i32 {
    #[cfg(feature = "random")]
    {
        crate::ops::rand_int(lo, hi)
    }
    #[cfg(not(feature = "random"))]
    {
        let _ = (lo, hi);
        i32::MIN
    }
}

/// Return milliseconds since the Unix epoch (1970-01-01T00:00:00 UTC).
/// Returns `i64::MIN` (null) if the system clock reports a time before the epoch.
/// Bytecode equivalent: `n_now` in `src/native.rs`.
#[cfg(not(feature = "wasm"))]
pub fn n_now(_stores: &mut Stores) -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(i64::MIN, |d| d.as_millis() as i64)
}

/// Bytecode equivalent: `n_now` in `src/native.rs`.
#[cfg(feature = "wasm")]
pub fn n_now(_stores: &mut Stores) -> i64 {
    crate::wasm::host_time_now()
}

/// Return microseconds elapsed since program start (monotonic clock).
/// Use for frame timing and benchmarks; unaffected by wall-clock adjustments.
/// Bytecode equivalent: `n_ticks` in `src/native.rs`.
#[cfg(not(target_arch = "wasm32"))]
pub fn n_ticks(stores: &mut Stores) -> i64 {
    stores.start_time.elapsed().as_micros() as i64
}

/// Bytecode equivalent: `n_ticks` in `src/native.rs`.  P137: gated on
/// target_arch, not the `wasm` feature — the `--html` build (wasm32,
/// no `wasm` feature) returns 0 because no host time bridge exists.
#[cfg(all(target_arch = "wasm32", feature = "wasm"))]
pub fn n_ticks(stores: &mut Stores) -> i64 {
    (crate::wasm::host_time_ticks() - stores.start_time_ms) * 1000
}

#[cfg(all(target_arch = "wasm32", not(feature = "wasm")))]
pub fn n_ticks(_stores: &mut Stores) -> i64 {
    0
}

/// Return the platform path separator as a loft character (`i32`).
/// Returns `'/'` (47) on Unix and `'\\'` (92) on Windows.
/// Bytecode equivalent: `n_path_sep` in `src/native.rs`.
pub fn n_path_sep(_stores: &mut Stores) -> i32 {
    crate::platform::sep() as i32
}

/// C60 piece 3: build a scratch u32-rec-nr vector from a hash,
/// ascending by the hash's key.  The parser-desugared `for e in h`
/// path calls this with the hash's type id as a compile-time constant
/// and iterates the result via Ordered (on=3).  Bytecode equivalent:
/// `n_hash_sorted` in `src/native.rs`.
pub fn n_hash_sorted(stores: &mut Stores, h: DbRef, tp: i32) -> DbRef {
    stores.build_hash_sorted_vec(&h, tp as u16)
}

/// Read the lock state of the store that owns the record pointed to by `r`.
/// Bytecode equivalent: `n_get_store_lock` in `src/native.rs`.
pub fn n_get_store_lock(stores: &mut Stores, r: DbRef) -> bool {
    stores.is_store_locked(&r)
}

/// Lock or unlock the store that owns the record pointed to by `r`.
/// Bytecode equivalent: `n_set_store_lock` in `src/native.rs`.
pub fn n_set_store_lock(stores: &mut Stores, r: DbRef, locked: bool) {
    if locked {
        stores.lock_store(&r);
    } else {
        stores.unlock_store(&r);
    }
}

/// Return a random integer in `[lo, hi]` (inclusive).
/// Returns `i32::MIN` (null) when `lo > hi`.
/// Bytecode equivalent: `n_rand` in `src/native.rs`.
pub fn n_rand(_stores: &mut Stores, lo: i32, hi: i32) -> i32 {
    cr_rand_int(lo, hi)
}

/// Return a vector of `n` integers `[0, 1, ..., n-1]` in a random order.
/// Returns an empty vector reference when `n <= 0`.
/// Bytecode equivalent: `n_rand_indices` in `src/native.rs`.
pub fn n_rand_indices(stores: &mut Stores, n: i32) -> DbRef {
    let count = if n == i32::MIN || n <= 0 {
        0usize
    } else {
        n as usize
    };
    // Build shuffled index list.  shuffle_ints is available under feature="random"
    // (PCG64 RNG) and feature="wasm" (host_random_int bridge); without either the
    // indices are returned in ascending order.
    #[allow(unused_mut)]
    let mut indices: Vec<i32> = (0..count as i32).collect();
    #[cfg(any(feature = "random", all(feature = "wasm", not(feature = "random"))))]
    crate::ops::shuffle_ints(&mut indices);
    // Allocate: vec_rec holds size + data, header_rec holds pointer to vec_rec.
    let base = stores.null();
    let vec_words = ((count as u32 * 4 + 15) / 8).max(1);
    let vec_cr = stores.claim(&base, vec_words);
    let vec_rec = vec_cr.rec;
    let header_cr = stores.claim(&base, 1);
    let header_rec = header_cr.rec;
    {
        let store = stores.store_mut(&base);
        store.set_u32_raw(vec_rec, 4, count as u32);
        for (i, &val) in indices.iter().enumerate() {
            store.set_i32_raw(vec_rec, 8 + i as u32 * 4, val);
        }
        store.set_u32_raw(header_rec, 4, vec_rec);
    }
    DbRef {
        store_nr: base.store_nr,
        rec: header_rec,
        pos: 4,
    }
}

/// Allocate a result vector of `n` elements, each `elem_size` bytes, and run
/// `worker(stores, element_dbref)` on every element, storing the result.
/// For native code, the caller passes a closure that calls the right Rust function.
/// Returns a `DbRef` to the result store; the caller frees it with `OpFreeRef`.
/// Memory layout matches bytecode `n_parallel_for`:
///   `header_rec`, `pos=4` → `i32` pointing to `vec_rec`
///   `vec_rec`, `pos=4`    → element count (`n`)
///   `vec_rec`, `pos=8+i*S` → element `i`  (`S` = 4 int / 8 long+float / 1 bool bytes)
pub fn n_parallel_for_native<F>(
    stores: &mut Stores,
    input: DbRef,
    elem_size: i32,
    return_size: i32,
    _threads: i32,
    mut worker: F,
) -> DbRef
where
    F: FnMut(&mut Stores, DbRef) -> i64,
{
    let n = vector::length_vector(&input, &stores.allocations) as usize;
    let return_sz = return_size.clamp(1, 8) as u32;
    let result_db = stores.null();
    let vec_words = ((n as u32) * return_sz + 15) / 8;
    let vec_cr = stores.claim(&result_db, vec_words.max(1));
    let vec_rec = vec_cr.rec;
    let header_cr = stores.claim(&result_db, 1);
    let header_rec = header_cr.rec;
    // Collect results.
    let mut fld = 8u32;
    for i in 0..n {
        let elm = {
            let v_rec = crate::keys::store(&input, &stores.allocations)
                .get_u32_raw(input.rec, input.pos);
            DbRef {
                store_nr: input.store_nr,
                rec: v_rec,
                pos: 8 + (i as u32) * (elem_size as u32),
            }
        };
        let val = worker(stores, elm);
        let store = stores.store_mut(&result_db);
        match return_sz {
            8 => {
                store.set_long(vec_rec, fld, val);
            }
            1 => {
                store.set_byte(vec_rec, fld, 0, val as i32);
            }
            _ => {
                store.set_i32_raw(vec_rec, fld, val as i32);
            }
        }
        fld += return_sz;
    }
    {
        let store = stores.store_mut(&result_db);
        store.set_u32_raw(vec_rec, 4, n as u32);
        store.set_u32_raw(header_rec, 4, vec_rec);
    }
    DbRef {
        store_nr: result_db.store_nr,
        rec: header_rec,
        pos: 4,
    }
}

/// Text-returning variant of `n_parallel_for_native`.  The worker closure returns
/// an owned `String`; each result is stored in the result store via `set_str` and
/// the 4-byte text position is written into the result vector.
pub fn n_parallel_for_text_native<F>(
    stores: &mut Stores,
    input: DbRef,
    elem_size: i32,
    _return_size: i32,
    _threads: i32,
    mut worker: F,
) -> DbRef
where
    F: FnMut(&mut Stores, DbRef) -> String,
{
    let n = vector::length_vector(&input, &stores.allocations) as usize;
    let result_db = stores.null();
    let vec_words = ((n as u32) * 4 + 15) / 8;
    let vec_cr = stores.claim(&result_db, vec_words.max(1));
    let vec_rec = vec_cr.rec;
    let header_cr = stores.claim(&result_db, 1);
    let header_rec = header_cr.rec;
    for i in 0..n {
        let elm = {
            let v_rec = crate::keys::store(&input, &stores.allocations)
                .get_u32_raw(input.rec, input.pos);
            DbRef {
                store_nr: input.store_nr,
                rec: v_rec,
                pos: 8 + (i as u32) * (elem_size as u32),
            }
        };
        let s = worker(stores, elm);
        let store = stores.store_mut(&result_db);
        let s_pos = store.set_str(&s);
        store.set_u32_raw(vec_rec, 8 + (i as u32) * 4, s_pos);
    }
    {
        let store = stores.store_mut(&result_db);
        store.set_u32_raw(vec_rec, 4, n as u32);
        store.set_u32_raw(header_rec, 4, vec_rec);
    }
    DbRef {
        store_nr: result_db.store_nr,
        rec: header_rec,
        pos: 4,
    }
}

/// Reference/struct-returning variant of `n_parallel_for_native`.  The worker closure
/// returns a `DbRef` pointing to a newly created struct.  Each result is deep-copied
/// (raw bytes + owned sub-fields) inline into the result vector so that `OpGetVector`
/// returns a `DbRef` that supports field access without extra indirection.
///
/// `struct_size` is the inline byte size of the struct (from `stores.size(known_type)`).
/// `known_type` is the struct's type id for `copy_block` / `copy_claims`.
pub fn n_parallel_for_ref_native<F>(
    stores: &mut Stores,
    input: DbRef,
    elem_size: i32,
    struct_size: i32,
    known_type: i32,
    _threads: i32,
    mut worker: F,
) -> DbRef
where
    F: FnMut(&mut Stores, DbRef) -> DbRef,
{
    let n = vector::length_vector(&input, &stores.allocations) as usize;
    let sz = struct_size as u32;
    let kt = known_type as u16;
    let result_db = stores.null();
    let vec_words = ((n as u32) * sz + 15) / 8;
    let vec_cr = stores.claim(&result_db, vec_words.max(1));
    let vec_rec = vec_cr.rec;
    let header_cr = stores.claim(&result_db, 1);
    let header_rec = header_cr.rec;
    for i in 0..n {
        let elm = {
            let v_rec = crate::keys::store(&input, &stores.allocations)
                .get_u32_raw(input.rec, input.pos);
            DbRef {
                store_nr: input.store_nr,
                rec: v_rec,
                pos: 8 + (i as u32) * (elem_size as u32),
            }
        };
        let src_ref = worker(stores, elm);
        let dest = DbRef {
            store_nr: result_db.store_nr,
            rec: vec_rec,
            pos: 8 + (i as u32) * sz,
        };
        stores.copy_block(&src_ref, &dest, sz);
        stores.copy_claims(&src_ref, &dest, kt);
    }
    {
        let store = stores.store_mut(&result_db);
        store.set_u32_raw(vec_rec, 4, n as u32);
        store.set_u32_raw(header_rec, 4, vec_rec);
    }
    DbRef {
        store_nr: result_db.store_nr,
        rec: header_rec,
        pos: 4,
    }
}

/// Read a struct/reference result element from a `n_parallel_for_ref_native` result vector.
/// Returns a `DbRef` pointing to the inline struct data at the given index.
pub fn n_parallel_get_ref(stores: &mut Stores, r: DbRef, idx: i32, struct_size: i32) -> DbRef {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_u32_raw(r.rec, r.pos);
    DbRef {
        store_nr: r.store_nr,
        rec: v_rec,
        pos: 8 + (idx as u32) * (struct_size as u32),
    }
}

/// Read an integer result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_int(stores: &mut Stores, r: DbRef, idx: i32) -> i32 {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_u32_raw(r.rec, r.pos);
    stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_i32_raw(v_rec, 8 + (idx as u32) * 4)
}

/// Read a long result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_long(stores: &mut Stores, r: DbRef, idx: i32) -> i64 {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_u32_raw(r.rec, r.pos);
    stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_long(v_rec, 8 + (idx as u32) * 8)
}

/// Read a float result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_float(stores: &mut Stores, r: DbRef, idx: i32) -> f64 {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_u32_raw(r.rec, r.pos);
    let bits = stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_long(v_rec, 8 + (idx as u32) * 8);
    f64::from_bits(bits as u64)
}

/// Read a boolean result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_bool(stores: &mut Stores, r: DbRef, idx: i32) -> bool {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_u32_raw(r.rec, r.pos);
    stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_byte(v_rec, 8 + idx as u32, 0)
        != 0
}

// ── N8b.1: Native coroutine runtime ─────────────────────────────────────────

/// Sentinel `store_nr` for `DbRef`s that point to native coroutine generators.
/// Must not clash with any real `Stores` allocation (stores use 0..`Stores::max`).
pub const NATIVE_COROUTINE_STORE: u16 = 0xFFFD;

/// Return value from `LoftCoroutine::next_i64` when the generator is exhausted.
///
/// For integer-yielding generators (`iterator<integer>`), the for-loop termination
/// uses `op_conv_bool_from_int(val as i32)`, which returns `false` only when
/// `val as i32 == i32::MIN`.  Using `i32::MIN as i64` ensures the cast lands on
/// the integer null sentinel so the loop breaks correctly.
///
/// (Long-yielding generators need `i64::MIN` instead; deferred to N8b.3 — only
/// integer generators are tested by N8b.1/N8b.2.)
pub const COROUTINE_EXHAUSTED: i64 = i32::MIN as i64;

/// Trait implemented by every native generator (state-machine struct).
/// The generated `fn {name}(stores, args) -> Box<dyn LoftCoroutine>` factory
/// constructs an instance; `alloc_coroutine` stores it and returns a `DbRef`.
pub trait LoftCoroutine {
    /// Advance the generator one step.  Returns the yielded value as `i64`,
    /// or `COROUTINE_EXHAUSTED` when no further values are available.
    fn next_i64(&mut self, stores: &mut Stores) -> i64;
}

std::thread_local! {
    /// Per-thread storage for native coroutine instances.
    /// Slot 0 is always `None` and acts as the null sentinel.
    static NATIVE_COROUTINES: std::cell::RefCell<Vec<Option<Box<dyn LoftCoroutine>>>> =
        std::cell::RefCell::new(vec![None]);
}

/// Store a native coroutine generator and return a `DbRef` that identifies it.
#[must_use]
pub fn alloc_coroutine(coro: Box<dyn LoftCoroutine>) -> DbRef {
    NATIVE_COROUTINES.with(|c| {
        let mut coroutines = c.borrow_mut();
        for (i, slot) in coroutines.iter_mut().enumerate().skip(1) {
            if slot.is_none() {
                *slot = Some(coro);
                return DbRef {
                    store_nr: NATIVE_COROUTINE_STORE,
                    rec: i as u32,
                    pos: 0,
                };
            }
        }
        let idx = coroutines.len();
        coroutines.push(Some(coro));
        DbRef {
            store_nr: NATIVE_COROUTINE_STORE,
            rec: idx as u32,
            pos: 0,
        }
    })
}

/// Advance a native coroutine and return the yielded value as `i64`.
/// Frees the coroutine slot automatically when it is exhausted.
pub fn coroutine_next_i64(gen_ref: DbRef, stores: &mut Stores) -> i64 {
    NATIVE_COROUTINES.with(|c| {
        let mut coroutines = c.borrow_mut();
        let idx = gen_ref.rec as usize;
        if let Some(slot) = coroutines.get_mut(idx)
            && let Some(coro) = slot.as_mut()
        {
            let val = coro.next_i64(stores);
            if val == COROUTINE_EXHAUSTED {
                coroutines[idx] = None; // free on exhaustion (P2-R7 parity)
            }
            val
        } else {
            COROUTINE_EXHAUSTED
        }
    })
}

/// Test whether a native coroutine has been exhausted (its slot freed).
#[must_use]
pub fn coroutine_is_exhausted(gen_ref: DbRef) -> bool {
    NATIVE_COROUTINES.with(|c| {
        let coroutines = c.borrow();
        let idx = gen_ref.rec as usize;
        coroutines.get(idx).is_none_or(Option::is_none)
    })
}

// ── FS-B  File-system dispatch helpers ───────────────────────────────────────
// Called from fill.rs (interpreter) and generated native code alike.
// Paths: interpreter uses `crate::codegen_runtime::*`; native uses
// `use loft::codegen_runtime::*` so these names resolve in both contexts.
// Under `--features wasm` each function calls the host bridge; otherwise it
// calls the real filesystem.

/// Delete `path`.  Returns `true` on success.
#[must_use]
pub fn fs_delete(path: &str) -> bool {
    #[cfg(feature = "wasm")]
    {
        crate::wasm::host_fs_delete(path) == 0
    }
    #[cfg(not(feature = "wasm"))]
    {
        std::fs::remove_file(path).is_ok()
    }
}

/// Rename / move `from` to `to`.  Returns `true` on success.
#[must_use]
pub fn fs_move(from: &str, to: &str) -> bool {
    #[cfg(feature = "wasm")]
    {
        crate::wasm::host_fs_move(from, to) == 0
    }
    #[cfg(not(feature = "wasm"))]
    {
        std::fs::rename(from, to).is_ok()
    }
}

/// Create directory `path`.  Returns `true` on success.
#[must_use]
pub fn fs_mkdir(path: &str) -> bool {
    #[cfg(feature = "wasm")]
    {
        crate::wasm::host_fs_mkdir(path) == 0
    }
    #[cfg(not(feature = "wasm"))]
    {
        std::fs::create_dir(path).is_ok()
    }
}

/// Create directory `path` and all parents.  Returns `true` on success.
#[must_use]
pub fn fs_mkdir_all(path: &str) -> bool {
    #[cfg(feature = "wasm")]
    {
        crate::wasm::host_fs_mkdir_all(path) == 0
    }
    #[cfg(not(feature = "wasm"))]
    {
        std::fs::create_dir_all(path).is_ok()
    }
}

/// Store a closure DbRef associated with a lambda definition number.
/// Called in generated native code when `OpStoreClosure` appears in the IR,
/// immediately before the fn-ref variable is stored.
/// The closure is later retrieved by `OpGetClosure` in the match-dispatch arm.
pub fn OpStoreClosure(stores: &mut Stores, d_nr: u32, closure: DbRef) {
    stores.closure_map.insert(d_nr, closure);
}

/// Retrieve the closure DbRef for a lambda definition number.
/// Called in generated native code inside match-dispatch arms for closure-capturing lambdas.
/// Returns a null DbRef if no closure was registered for `d_nr`.
#[must_use]
pub fn OpGetClosure(stores: &Stores, d_nr: u32) -> DbRef {
    stores.closure_map.get(&d_nr).copied().unwrap_or(DbRef {
        store_nr: 0,
        rec: 0,
        pos: 0,
    })
}

// ── Shadow call stack for native stack_trace() ──────────────────────────────

// Thread-local shadow call stack used by native-compiled loft code.
// Each entry is (function_name, source_file, line_number).
// Generated code calls `cr_call_push` / `cr_call_pop` around every function body.
thread_local! {
    static CALL_STACK: RefCell<Vec<(&'static str, &'static str, u32)>> = const { RefCell::new(Vec::new()) };
}

/// Push a frame onto the shadow call stack.  Called at the start of every
/// generated function body.  The `&'static str` arguments are string literals
/// embedded in the generated Rust code.
#[inline]
pub fn cr_call_push(name: &'static str, file: &'static str, line: u32) {
    CALL_STACK.with(|s| s.borrow_mut().push((name, file, line)));
}

/// Pop a frame from the shadow call stack.  Called at the end of every
/// generated function body (including early returns via a drop guard).
#[inline]
pub fn cr_call_pop() {
    CALL_STACK.with(|s| s.borrow_mut().pop());
}

/// RAII guard that pops the shadow call stack on drop, ensuring the stack
/// stays balanced even when the function returns early.
pub struct CallGuard;

impl Drop for CallGuard {
    fn drop(&mut self) {
        cr_call_pop();
    }
}

/// Native implementation of `stack_trace()`.
/// Reads the thread-local shadow call stack and builds `vector<StackFrame>`
/// using the same stores API as the interpreter implementation in `native.rs`.
pub fn n_stack_trace(stores: &mut Stores) -> DbRef {
    let snapshot: Vec<(&str, &str, u32)> = CALL_STACK.with(|s| s.borrow().clone());

    let sf_elm = stores.name("StackFrame");
    let sf_size = u32::from(stores.size(sf_elm));
    let fn_pos = u32::from(stores.position(sf_elm, "function"));
    let file_pos = u32::from(stores.position(sf_elm, "file"));
    let line_pos = u32::from(stores.position(sf_elm, "line"));
    let args_pos = u32::from(stores.position(sf_elm, "arguments"));
    let vars_pos = u32::from(stores.position(sf_elm, "variables"));
    let vec = stores.database(sf_size);
    stores.store_mut(&vec).set_u32_raw(vec.rec, vec.pos, 0);

    for (fn_name, file, line) in &snapshot {
        let elm = crate::vector::vector_append(&vec, sf_size, &mut stores.allocations);
        let fn_str = stores.store_mut(&vec).set_str(fn_name);
        stores
            .store_mut(&vec)
            .set_u32_raw(elm.rec, elm.pos + fn_pos, fn_str);
        let file_str = stores.store_mut(&vec).set_str(file);
        stores
            .store_mut(&vec)
            .set_u32_raw(elm.rec, elm.pos + file_pos, file_str);
        stores
            .store_mut(&vec)
            .set_int(elm.rec, elm.pos + line_pos, i64::from(*line));
        // Zero the arguments and variables vector fields.
        stores
            .store_mut(&vec)
            .set_u32_raw(elm.rec, elm.pos + args_pos, 0);
        stores
            .store_mut(&vec)
            .set_u32_raw(elm.rec, elm.pos + vars_pos, 0);
        crate::vector::vector_finish(&vec, &mut stores.allocations);
    }
    vec
}

// ── LoftStore construction for native codegen ───────────────────────────
// When native codegen calls `extern "C"` functions that take `LoftStore`,
// it needs to build one from `&mut Stores`.  These helpers provide that.

std::thread_local! {
    static CODEGEN_STORES: std::cell::Cell<*mut Stores> =
        const { std::cell::Cell::new(std::ptr::null_mut()) };
}

unsafe extern "C" fn _ffi_claim(ctx: loft_ffi::LoftStoreCtx, words: u32) -> u32 {
    let store_nr = ctx._opaque as usize as u16;
    CODEGEN_STORES.with(|c| {
        let stores = unsafe { &mut *c.get() };
        stores.allocations[store_nr as usize].claim(words)
    })
}

unsafe extern "C" fn _ffi_reload(
    ctx: loft_ffi::LoftStoreCtx,
    out_ptr: *mut *mut u8,
    out_size: *mut u32,
) {
    let store_nr = ctx._opaque as usize as u16;
    CODEGEN_STORES.with(|c| {
        let stores = unsafe { &*c.get() };
        let store = &stores.allocations[store_nr as usize];
        unsafe {
            *out_ptr = store.base_ptr();
            *out_size = store.capacity_words();
        }
    });
}

unsafe extern "C" fn _ffi_resize(ctx: loft_ffi::LoftStoreCtx, rec: u32, words: u32) -> u32 {
    let store_nr = ctx._opaque as usize as u16;
    CODEGEN_STORES.with(|c| {
        let stores = unsafe { &mut *c.get() };
        stores.allocations[store_nr as usize].resize(rec, words)
    })
}

/// Build a `LoftStore` handle for calling `extern "C"` native functions that
/// need store access.  Sets a thread-local pointer so the FFI callbacks can
/// reach back into the stores.
pub fn make_loft_store(stores: &mut Stores, store_nr: u16) -> loft_ffi::LoftStore {
    CODEGEN_STORES.with(|c| c.set(std::ptr::from_mut::<Stores>(stores)));
    let store = &stores.allocations[store_nr as usize];
    loft_ffi::LoftStore {
        ptr: store.base_ptr(),
        size: store.capacity_words(),
        ctx: loft_ffi::LoftStoreCtx {
            _opaque: store_nr as usize as *mut (),
        },
        claim_fn: Some(_ffi_claim),
        reload_fn: Some(_ffi_reload),
        resize_fn: Some(_ffi_resize),
    }
}
