// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Runtime helper functions for native Rust code generated by `generation.rs`.
//!
//! The bytecode interpreter implements these operations as opcodes that read
//! parameters from the bytecode stream and manipulate the stack.  Generated
//! native code calls these wrapper functions directly with explicit arguments.
//!
//! **Interpreter safety:** This module is purely additive — it does not modify
//! any interpreter code path.  It only re-exposes `Stores` methods with the
//! signatures that generated code expects.

#![allow(non_snake_case)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::cast_sign_loss)]
#![allow(clippy::doc_markdown)]

use crate::database::{ShowDb, Stores};
use crate::keys::DbRef;

/// Allocate a database root record for the given type.
/// The generated code calls this as `OpDatabase(stores, var, tp)` where `var` is
/// passed by value (DbRef).  The function allocates into the store referenced by
/// `db`, then returns the updated DbRef.
/// Bytecode equivalent: `OpDatabase` in `src/state/io.rs:319`.
pub fn OpDatabase(stores: &mut Stores, mut db: DbRef, db_tp: i32) -> DbRef {
    let db_tp = db_tp as u16;
    let size = stores.size(db_tp);
    stores.clear(&db);
    let r = stores.claim(&db, u32::from(size));
    stores.store_mut(&r).set_int(r.rec, 4, i32::from(db_tp));
    stores.set_default_value(db_tp, &r);
    db.store_nr = r.store_nr;
    db.rec = 1;
    db.pos = 8;
    db
}

/// Create a new record element inside a vector/sorted/index collection.
/// Returns a `DbRef` pointing to the new element with default field values.
/// Bytecode equivalent: `OpNewRecord` in `src/state/io.rs:336`.
pub fn OpNewRecord(stores: &mut Stores, data: DbRef, parent_tp: i32, fld: i32) -> DbRef {
    let parent_tp = parent_tp as u16;
    let fld = fld as u16;
    let new_value = stores.record_new(&data, parent_tp, fld);
    stores.set_default_value(
        if fld == u16::MAX {
            stores.content(parent_tp)
        } else {
            stores.content(stores.field_type(parent_tp, fld))
        },
        &new_value,
    );
    new_value
}

/// Finalize a record after its fields have been assigned.
/// For sorted/index collections this inserts the record at the correct position.
/// Bytecode equivalent: `OpFinishRecord` in `src/state/io.rs:772`.
pub fn OpFinishRecord(stores: &mut Stores, data: DbRef, record: DbRef, parent_tp: i32, fld: i32) {
    stores.record_finish(&data, &record, parent_tp as u16, fld as u16);
}

/// Free a database reference.  Closes any associated file handle first.
/// Bytecode equivalent: `OpFreeRef` in `src/state/io.rs:262`.
pub fn OpFreeRef(stores: &mut Stores, db: DbRef) {
    if db.rec != 0
        && let Some(&file_type) = stores.names.get("File")
    {
        let stored_type = stores.store(&db).get_int(db.rec, 4) as u16;
        if stored_type == file_type {
            let file_ref = stores.store(&db).get_int(db.rec, db.pos + 28);
            if file_ref != i32::MIN && (file_ref as usize) < stores.files.len() {
                stores.files[file_ref as usize] = None;
            }
        }
    }
    stores.free(&db);
}

/// Format a database record as text and append it to the output string.
/// Bytecode equivalent: `OpFormatDatabase` in `src/state/io.rs:278`.
pub fn OpFormatDatabase(
    stores: &mut Stores,
    output: &mut String,
    record: DbRef,
    db_tp: i32,
    db_format: i32,
) {
    let mut s = String::new();
    ShowDb {
        stores,
        store: record.store_nr,
        rec: record.rec,
        pos: record.pos,
        known_type: db_tp as u16,
        pretty: db_format & 1 > 0,
        json: db_format & 2 > 0,
    }
    .write(&mut s, 0);
    output.push_str(&s);
}

/// Look up a record in a collection by key values.
/// Bytecode equivalent: `OpGetRecord` in `src/state/io.rs:353`.
pub fn OpGetRecord(
    stores: &mut Stores,
    data: DbRef,
    db_tp: i32,
    key: &[crate::keys::Content],
) -> DbRef {
    if data.rec == 0 {
        DbRef {
            store_nr: data.store_nr,
            rec: 0,
            pos: 0,
        }
    } else {
        stores.find(&data, db_tp as u16, key)
    }
}

/// Extract a substring from a text value.
/// Bytecode equivalent: `OpGetTextSub` in `src/fill.rs`.
#[must_use]
pub fn OpGetTextSub(text: &str, from: i32, till: i32) -> &str {
    #![allow(clippy::cast_possible_wrap)]
    let len = text.len() as i32;
    let f = from.max(0).min(len) as usize;
    let t = till.max(0).min(len) as usize;
    if f >= t { "" } else { &text[f..t] }
}

/// Return the byte size of a database record's type.
/// Bytecode equivalent: `OpSizeofRef` in `src/state/io.rs:290`.
#[must_use]
pub fn OpSizeofRef(stores: &Stores, db: DbRef) -> i32 {
    if db.rec == 0 {
        0
    } else {
        let tp = stores.store(&db).get_int(db.rec, 4) as u16;
        i32::from(stores.size(tp))
    }
}
