// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Runtime helper functions for native Rust code generated by `generation.rs`.
//!
//! The bytecode interpreter implements these operations as opcodes that read
//! parameters from the bytecode stream and manipulate the stack.  Generated
//! native code calls these wrapper functions directly with explicit arguments.
//!
//! **Interpreter safety:** This module is purely additive — it does not modify
//! any interpreter code path.  It only re-exposes `Stores` methods with the
//! signatures that generated code expects.

#![allow(non_snake_case)]
#![allow(clippy::cast_possible_truncation)]
#![allow(clippy::cast_sign_loss)]
#![allow(clippy::doc_markdown)]

use crate::database::{ShowDb, Stores};
use crate::keys::{Content, DbRef, Key};
use crate::ops;
use crate::tree;
use crate::vector;
use std::fs::{File, OpenOptions};
use std::io::{Read, Seek, SeekFrom, Write as _};
use std::time::{SystemTime, UNIX_EPOCH};

/// Allocate a database root record for the given type.
/// The generated code calls this as `OpDatabase(stores, var, tp)` where `var` is
/// passed by value (DbRef).  The function allocates into the store referenced by
/// `db`, then returns the updated DbRef.
/// Bytecode equivalent: `OpDatabase` in `src/state/io.rs:319`.
pub fn OpDatabase(stores: &mut Stores, mut db: DbRef, db_tp: i32) -> DbRef {
    let db_tp = db_tp as u16;
    let size = stores.size(db_tp);
    if db.store_nr == u16::MAX {
        // Null sentinel (no real store yet) — allocate a fresh one.
        db = stores.null();
    }
    stores.clear(&db);
    let r = stores.claim(&db, u32::from(size));
    stores.store_mut(&r).set_int(r.rec, 4, i32::from(db_tp));
    stores.set_default_value(db_tp, &r);
    db.store_nr = r.store_nr;
    db.rec = 1;
    db.pos = 8;
    db
}

/// Create a new record element inside a vector/sorted/index collection.
/// Returns a `DbRef` pointing to the new element with default field values.
/// Bytecode equivalent: `OpNewRecord` in `src/state/io.rs:336`.
pub fn OpNewRecord(stores: &mut Stores, data: DbRef, parent_tp: i32, fld: i32) -> DbRef {
    let parent_tp = parent_tp as u16;
    let fld = fld as u16;
    let new_value = stores.record_new(&data, parent_tp, fld);
    stores.set_default_value(
        if fld == u16::MAX {
            stores.content(parent_tp)
        } else {
            stores.content(stores.field_type(parent_tp, fld))
        },
        &new_value,
    );
    new_value
}

/// Finalize a record after its fields have been assigned.
/// For sorted/index collections this inserts the record at the correct position.
/// Bytecode equivalent: `OpFinishRecord` in `src/state/io.rs:772`.
pub fn OpFinishRecord(stores: &mut Stores, data: DbRef, record: DbRef, parent_tp: i32, fld: i32) {
    stores.record_finish(&data, &record, parent_tp as u16, fld as u16);
}

/// Free a database reference.  Closes any associated file handle first.
/// Bytecode equivalent: `OpFreeRef` in `src/state/io.rs:262`.
/// The `name` argument is the loft variable name (e.g. `"var_p"`); it appears in
/// `LOFT_STORE_LOG` output for diagnosing LIFO store-free order violations.
pub fn OpFreeRef(stores: &mut Stores, db: DbRef, name: &str) {
    if db.rec != 0
        && let Some(&file_type) = stores.names.get("File")
    {
        let stored_type = stores.store(&db).get_int(db.rec, 4) as u16;
        if stored_type == file_type {
            let file_ref = stores.store(&db).get_int(db.rec, db.pos + 28);
            if file_ref != i32::MIN && (file_ref as usize) < stores.files.len() {
                stores.files[file_ref as usize] = None;
            }
        }
    }
    stores.free_named(&db, name);
}

/// Format a database record as text and append it to the output string.
/// Bytecode equivalent: `OpFormatDatabase` in `src/state/io.rs:278`.
pub fn OpFormatDatabase(
    stores: &mut Stores,
    output: &mut String,
    record: DbRef,
    db_tp: i32,
    db_format: i32,
) {
    let mut s = String::new();
    ShowDb {
        stores,
        store: record.store_nr,
        rec: record.rec,
        pos: record.pos,
        known_type: db_tp as u16,
        pretty: db_format & 1 > 0,
        json: db_format & 2 > 0,
    }
    .write(&mut s, 0);
    output.push_str(&s);
}

/// Look up a record in a collection by key values.
/// Bytecode equivalent: `OpGetRecord` in `src/state/io.rs:353`.
pub fn OpGetRecord(
    stores: &mut Stores,
    data: DbRef,
    db_tp: i32,
    key: &[crate::keys::Content],
) -> DbRef {
    if data.rec == 0 {
        DbRef {
            store_nr: data.store_nr,
            rec: 0,
            pos: 0,
        }
    } else {
        stores.find(&data, db_tp as u16, key)
    }
}

/// Extract a substring from a text value.
///
/// `from` and `till` are **byte** indices into the UTF-8 string (matching the
/// bytecode interpreter in `src/state/text.rs`):
/// - `from` is snapped *backward* to the start of its containing character if
///   it points into the middle of a multi-byte sequence.
/// - `till` is snapped *forward* past continuation bytes so it lands on the
///   next character boundary.
/// - A negative `till` counts from the end of the string (`till += len`).
///
/// Bytecode equivalent: `State::get_text_sub` in `src/state/text.rs`.
#[must_use]
pub fn OpGetTextSub(text: &str, from: i32, till: i32) -> &str {
    #![allow(clippy::cast_possible_wrap)]
    let bytes = text.as_bytes();
    let len = bytes.len() as i32;
    if from < 0 || from >= len {
        return "";
    }
    // Snap `from` backward to the start of the current character.
    let mut f = from as usize;
    while f > 0 && bytes[f] & 0xC0 == 0x80 {
        f -= 1;
    }
    // Resolve negative `till` to a forward byte offset.
    let t_raw = if till < 0 { len + till } else { till };
    if t_raw <= f as i32 {
        return "";
    }
    // Clamp to string length.
    let mut t = t_raw.min(len) as usize;
    // Snap `till` forward past any continuation bytes so it lands on a
    // character boundary (mirrors the interpreter behaviour).
    while t < bytes.len() && bytes[t] & 0xC0 == 0x80 {
        t += 1;
    }
    &text[f..t]
}

/// Return the byte size of a database record's type.
/// Bytecode equivalent: `OpSizeofRef` in `src/state/io.rs:290`.
#[must_use]
pub fn OpSizeofRef(stores: &Stores, db: DbRef) -> i32 {
    if db.rec == 0 {
        0
    } else {
        let tp = stores.store(&db).get_int(db.rec, 4) as u16;
        i32::from(stores.size(tp))
    }
}

/// Parse a text representation into a database record.
/// Bytecode equivalent: `State::db_from_text` in `src/state/io.rs:780`.
#[must_use]
pub fn db_from_text(stores: &mut Stores, val: &str, db_tp: u16) -> DbRef {
    let db = stores.database(8);
    let into = DbRef {
        store_nr: db.store_nr,
        rec: db.rec,
        pos: 8,
    };
    stores.set_default_value(db_tp, &into);
    let mut pos = 0;
    if stores.parsing(val, &mut pos, db_tp, db_tp, u16::MAX, &into) {
        into
    } else {
        DbRef {
            store_nr: db.store_nr,
            rec: 0,
            pos: 0,
        }
    }
}

/// Deep-copy a database record: copies the raw bytes and duplicates
/// all owned sub-structures (text fields, vectors, etc.).
/// Bytecode equivalent: `State::copy_record` in `src/state/io.rs:697`.
pub fn OpCopyRecord(stores: &mut Stores, data: DbRef, to: DbRef, tp: i32) {
    let tp = tp as u16;
    let size = u32::from(stores.size(tp));
    stores.copy_block(&data, &to, size);
    stores.copy_claims(&data, &to, tp);
}

/// Sort a vector in-place using the element type's natural ordering.
/// Bytecode equivalent: `sort_vector` in `src/fill.rs:1835`.
pub fn OpSortVector(stores: &mut Stores, data: DbRef, db_tp: i32) {
    let db_tp = db_tp as u16;
    let elem_size = stores.size(db_tp);
    let is_float = db_tp == 2 || db_tp == 3;
    vector::sort_vector(&data, elem_size, is_float, &mut stores.allocations);
}

/// Insert a new default-valued element at `index` in a vector, shifting later elements right.
/// Returns a `DbRef` pointing to the newly inserted element.
/// Bytecode equivalent: `State::insert_vector` in `src/state/io.rs:819`.
pub fn OpInsertVector(
    stores: &mut Stores,
    data: DbRef,
    size: i32,
    index: i32,
    db_tp: i32,
) -> DbRef {
    let new_value = vector::insert_vector(&data, size as u32, index, &mut stores.allocations);
    stores.set_default_value(db_tp as u16, &new_value);
    new_value
}

/// Return the UTF-8 byte length of a character (encoded as `i32` in loft).
/// Returns 0 for the null character sentinel.
/// Bytecode equivalent: `State::length_character` in `src/state/text.rs:54`.
#[must_use]
pub fn OpLengthCharacter(_stores: &mut Stores, c: i32) -> i32 {
    let ch = ops::to_char(c);
    if ch == '\0' {
        0
    } else {
        i32::try_from(ch.len_utf8()).unwrap_or(0)
    }
}

/// Pack a (current-position, finish) pair into a single i64 iterator state.
/// High 32 bits = finish; low 32 bits = cur.
/// `finish == u32::MAX` signals that iteration is complete.
fn pack_iter(cur: u32, finish: u32) -> i64 {
    ((u64::from(finish) << 32) | u64::from(cur)).cast_signed()
}

/// Build a minimal DbRef pointing at record `rec` with field offset `pos`.
fn iter_ref(data: &DbRef, rec: u32, pos: u16) -> DbRef {
    DbRef {
        store_nr: data.store_nr,
        rec,
        pos: u32::from(pos),
    }
}

/// Initialize a sorted/index iterator state and return it as a packed `i64`.
///
/// `on` encodes collection type and flags:
/// - bits 0–5: collection type (1 = red-black tree / index, 2 = sorted vector)
/// - bit 6: reverse iteration
/// - bit 7: inclusive end (if clear, end is exclusive)
///
/// `arg` is the element size in bytes (sorted) or the tree-fields offset (index).
/// `keys` describes the key fields in the collection type.
/// `from` / `till` are the from/till key values; empty slices mean start/end of collection.
///
/// The returned `i64` is consumed by [`OpStep`].
/// Bytecode equivalent: `State::iterate` in `src/state/io.rs`.
#[must_use]
pub fn OpIterate(
    stores: &Stores,
    data: DbRef,
    on: i32,
    arg: i32,
    keys: &[Key],
    from: &[Content],
    till: &[Content],
) -> i64 {
    if data.rec == 0 {
        return pack_iter(u32::MAX, u32::MAX);
    }
    let reverse = (on & 64) != 0;
    let ex = (on & 128) == 0;
    let all = &stores.allocations;
    match on & 63 {
        2 => {
            // sorted vector: arg = element size in bytes
            let size = arg as u16;
            if reverse {
                let s = vector::sorted_find(&data, ex, size, all, keys, till).0 + u32::from(!ex);
                let f = vector::sorted_find(&data, ex, size, all, keys, from).0 + 1;
                pack_iter(s, f)
            } else {
                let s = vector::sorted_find(&data, true, size, all, keys, from).0;
                let start = if s == 0 { u32::MAX } else { s - 1 };
                let (t, cmp) = vector::sorted_find(&data, ex, size, all, keys, till);
                let finish = if ex || cmp { t } else { t + 1 };
                pack_iter(start, finish)
            }
        }
        1 => {
            // red-black tree / index: arg = fields offset
            let fields = arg as u16;
            let store = crate::keys::store(&data, all);
            if reverse {
                let t = tree::find(&data, ex, fields, all, keys, till);
                let start = if ex {
                    t
                } else {
                    tree::next(store, &iter_ref(&data, t, fields))
                };
                let f = tree::find(&data, ex, fields, all, keys, from);
                let finish = tree::next(store, &iter_ref(&data, f, fields));
                pack_iter(start, finish)
            } else {
                let start = tree::find(&data, true, fields, all, keys, from);
                let t = tree::find(&data, ex, fields, all, keys, till);
                let finish = if ex {
                    t
                } else {
                    tree::previous(store, &iter_ref(&data, t, fields))
                };
                pack_iter(start, finish)
            }
        }
        _ => pack_iter(u32::MAX, u32::MAX),
    }
}

/// Advance the iterator to the next element and return a `DbRef` pointing to it.
/// Returns a `DbRef` with `rec == 0` when iteration is complete.
///
/// `iter` is the mutable `i64` state returned by [`OpIterate`]; it is updated in place.
/// `on` and `arg` must match the corresponding `OpIterate` call.
///
/// Bytecode equivalent: `State::step` in `src/state/io.rs`.
pub fn OpStep(stores: &Stores, iter: &mut i64, data: DbRef, on: i32, arg: i32) -> DbRef {
    let mut cur = (*iter as u64) as u32;
    let mut finish = ((*iter as u64) >> 32) as u32;

    if data.rec == 0 || finish == u32::MAX {
        return stores.element_reference(&data, i32::MAX);
    }

    let reverse = (on & 64) != 0;
    let all = &stores.allocations;

    let result = match on & 63 {
        2 => {
            // sorted vector: arg = element size
            let mut pos = if cur == u32::MAX {
                i32::MAX
            } else {
                #[allow(clippy::cast_possible_wrap)]
                {
                    cur as i32
                }
            };
            if reverse {
                vector::vector_step_rev(&data, &mut pos, all);
                if pos == i32::MAX {
                    finish = u32::MAX;
                }
            } else {
                vector::vector_step(&data, &mut pos, all);
                if pos as u32 >= finish {
                    pos = i32::MAX;
                }
            }
            cur = pos as u32;
            let byte_pos = if pos == i32::MAX {
                i32::MAX
            } else {
                8 + pos * arg
            };
            if pos == i32::MAX {
                finish = u32::MAX;
            }
            stores.element_reference(&data, byte_pos)
        }
        1 => {
            // red-black tree / index: arg = fields offset
            let fields = arg as u16;
            let store = crate::keys::store(&data, all);
            let next_rec = if cur == 0 {
                if reverse {
                    tree::last(&data, fields, all).rec
                } else {
                    tree::first(&data, fields, all).rec
                }
            } else if reverse {
                tree::previous(store, &iter_ref(&data, cur, fields))
            } else {
                tree::next(store, &iter_ref(&data, cur, fields))
            };
            if next_rec == finish {
                finish = u32::MAX;
            }
            cur = next_rec;
            DbRef {
                store_nr: data.store_nr,
                rec: next_rec,
                pos: 8,
            }
        }
        _ => stores.element_reference(&data, i32::MAX),
    };

    *iter = pack_iter(cur, finish);
    result
}

/// Read the entire contents of a file into `content`, replacing its previous value.
/// If the file cannot be opened or read, `content` is cleared.
/// Bytecode equivalent: `State::get_file_text` in `src/state/io.rs`.
pub fn OpGetFileText(stores: &mut Stores, file: DbRef, content: &mut String) {
    if file.rec == 0 {
        return;
    }
    let file_path = {
        let store = stores.store(&file);
        store
            .get_str(store.get_int(file.rec, file.pos + 24) as u32)
            .to_owned()
    };
    content.clear();
    if let Ok(mut f) = File::open(&file_path)
        && f.read_to_string(content).is_err()
    {
        content.clear();
    }
}

/// Seek to `pos` bytes from the start of the file.
/// If the file handle is not yet open, stores `pos` in `#next` so the first
/// read/write applies the seek after opening.
/// Bytecode equivalent: `State::seek_file` in `src/state/io.rs`.
pub fn OpSeekFile(stores: &mut Stores, file: DbRef, pos: i64) {
    if file.rec == 0 {
        return;
    }
    let file_ref = stores.store(&file).get_int(file.rec, file.pos + 28);
    if file_ref == i32::MIN {
        stores
            .store_mut(&file)
            .set_long(file.rec, file.pos + 16, pos);
    } else if let Some(f) = &mut stores.files[file_ref as usize]
        && let Err(e) = f.seek(SeekFrom::Start(pos as u64))
    {
        eprintln!("file seek error: {e}");
    }
}

/// Return the byte size of the file, or `i64::MIN` if the size cannot be determined.
/// Bytecode equivalent: `State::size_file` in `src/state/io.rs`.
#[must_use]
pub fn OpSizeFile(stores: &Stores, file: DbRef) -> i64 {
    if file.rec == 0 {
        return i64::MIN;
    }
    let file_path = {
        let store = stores.store(&file);
        store
            .get_str(store.get_int(file.rec, file.pos + 24) as u32)
            .to_owned()
    };
    if let Ok(meta) = std::fs::metadata(&file_path) {
        meta.len().cast_signed()
    } else {
        i64::MIN
    }
}

/// Truncate (or extend) the file to `size` bytes.  Closes any open handle first.
/// Returns `true` on success, `false` on failure.
/// Bytecode equivalent: `State::truncate_file` in `src/state/io.rs`.
pub fn OpTruncateFile(stores: &mut Stores, file: DbRef, size: i64) -> bool {
    if file.rec == 0 {
        return false;
    }
    let file_path = {
        let store = stores.store(&file);
        store
            .get_str(store.get_int(file.rec, file.pos + 24) as u32)
            .to_owned()
    };
    // Close any open handle so resize starts from a clean state.
    let file_ref = stores.store(&file).get_int(file.rec, file.pos + 28);
    if file_ref != i32::MIN && (file_ref as usize) < stores.files.len() {
        stores.files[file_ref as usize] = None;
        stores
            .store_mut(&file)
            .set_int(file.rec, file.pos + 28, i32::MIN);
        stores
            .store_mut(&file)
            .set_long(file.rec, file.pos + 8, i64::MIN);
        stores
            .store_mut(&file)
            .set_long(file.rec, file.pos + 16, i64::MIN);
    }
    OpenOptions::new()
        .write(true)
        .open(&file_path)
        .and_then(|f| f.set_len(size as u64))
        .is_ok()
}

// ─── File I/O ─────────────────────────────────────────────────────────────────

/// Open (or reuse) a file handle for writing.  Returns the index into
/// `stores.files`, or `i32::MIN` on error.
#[allow(clippy::cast_possible_wrap)]
fn file_handle_write(stores: &mut Stores, file: &DbRef) -> i32 {
    let f_nr = stores.files.len() as i32;
    let file_ref = stores.store(file).get_int(file.rec, file.pos + 28);
    if file_ref != i32::MIN {
        return file_ref;
    }
    let (file_name, format) = {
        let store = stores.store(file);
        (
            store
                .get_str(store.get_int(file.rec, file.pos + 24) as u32)
                .to_owned(),
            store.get_byte(file.rec, file.pos + 32, 0),
        )
    };
    match File::create(&file_name) {
        Ok(f) => {
            stores
                .store_mut(file)
                .set_int(file.rec, file.pos + 28, f_nr);
            // If the file was NotExists, mark it as TextFile now that it exists.
            if format == 5 {
                stores
                    .store_mut(file)
                    .set_byte(file.rec, file.pos + 32, 0, 1);
            }
            stores.files.push(Some(f));
            f_nr
        }
        Err(e) => {
            eprintln!("file create error for {file_name:?}: {e}");
            i32::MIN
        }
    }
}

/// Open (or reuse) a file handle for reading, seeking to `initial_pos`.
/// Returns the index into `stores.files`, or `i32::MIN` on error.
#[allow(clippy::cast_possible_wrap)]
fn file_handle_read(stores: &mut Stores, file: &DbRef, initial_pos: i64) -> i32 {
    let f_nr = stores.files.len() as i32;
    let file_ref = stores.store(file).get_int(file.rec, file.pos + 28);
    if file_ref != i32::MIN {
        return file_ref;
    }
    let file_name = {
        let store = stores.store(file);
        store
            .get_str(store.get_int(file.rec, file.pos + 24) as u32)
            .to_owned()
    };
    match OpenOptions::new().read(true).open(&file_name) {
        Ok(mut f) => {
            if initial_pos > 0 {
                let _ = f.seek(SeekFrom::Start(initial_pos as u64));
            }
            stores
                .store_mut(file)
                .set_int(file.rec, file.pos + 28, f_nr);
            stores.files.push(Some(f));
            f_nr
        }
        Err(e) => {
            eprintln!("file open error for {file_name:?}: {e}");
            i32::MIN
        }
    }
}

/// Trait for types that can be written to / read from a loft binary or text file.
///
/// The `db_tp` parameter is the loft type index stored in `stores.types`; it
/// controls how many bytes are used and the interpretation (integer vs byte vs
/// short vs text, etc.).
pub trait FileVal {
    /// Serialise `self` into bytes that will be appended to the file.
    fn file_to_bytes(&self, stores: &Stores, db_tp: i32, little_endian: bool) -> Vec<u8>;
    /// Deserialise `bytes` (already read from the file) into `self`.
    fn file_from_bytes(&mut self, stores: &Stores, db_tp: i32, little_endian: bool, bytes: &[u8]);
}

impl FileVal for i32 {
    fn file_to_bytes(&self, stores: &Stores, db_tp: i32, little_endian: bool) -> Vec<u8> {
        let mut out = Vec::new();
        match db_tp {
            0 | 6 => {
                // integer | character — 4 bytes
                let b = if little_endian {
                    self.to_le_bytes()
                } else {
                    self.to_be_bytes()
                };
                out.extend_from_slice(&b);
            }
            4 => out.push(*self as u8), // boolean — 1 byte
            _ => match &stores.types[db_tp as usize].parts {
                crate::database::Parts::Byte(_, _) => out.push(*self as u8),
                crate::database::Parts::Short(_, _) => {
                    let v = *self as i16;
                    let b = if little_endian {
                        v.to_le_bytes()
                    } else {
                        v.to_be_bytes()
                    };
                    out.extend_from_slice(&b);
                }
                _ => {
                    let b = if little_endian {
                        self.to_le_bytes()
                    } else {
                        self.to_be_bytes()
                    };
                    out.extend_from_slice(&b);
                }
            },
        }
        out
    }

    fn file_from_bytes(&mut self, stores: &Stores, db_tp: i32, little_endian: bool, bytes: &[u8]) {
        match db_tp {
            0 | 6 => {
                if bytes.len() >= 4 {
                    *self = if little_endian {
                        i32::from_le_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                    } else {
                        i32::from_be_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                    };
                }
            }
            4 => {
                if let Some(&b) = bytes.first() {
                    *self = i32::from(b);
                }
            }
            _ => match &stores.types[db_tp as usize].parts {
                crate::database::Parts::Byte(_, _) => {
                    if let Some(&b) = bytes.first() {
                        *self = i32::from(b);
                    }
                }
                crate::database::Parts::Short(_, _) => {
                    if bytes.len() >= 2 {
                        let v = if little_endian {
                            i16::from_le_bytes(bytes[..2].try_into().unwrap_or([0; 2]))
                        } else {
                            i16::from_be_bytes(bytes[..2].try_into().unwrap_or([0; 2]))
                        };
                        *self = i32::from(v);
                    }
                }
                _ => {
                    if bytes.len() >= 4 {
                        *self = if little_endian {
                            i32::from_le_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                        } else {
                            i32::from_be_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
                        };
                    }
                }
            },
        }
    }
}

impl FileVal for i64 {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, little_endian: bool) -> Vec<u8> {
        if little_endian {
            self.to_le_bytes().to_vec()
        } else {
            self.to_be_bytes().to_vec()
        }
    }
    fn file_from_bytes(
        &mut self,
        _stores: &Stores,
        _db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        if bytes.len() >= 8 {
            *self = if little_endian {
                i64::from_le_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            } else {
                i64::from_be_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            };
        }
    }
}

impl FileVal for f32 {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, little_endian: bool) -> Vec<u8> {
        if little_endian {
            self.to_le_bytes().to_vec()
        } else {
            self.to_be_bytes().to_vec()
        }
    }
    fn file_from_bytes(
        &mut self,
        _stores: &Stores,
        _db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        if bytes.len() >= 4 {
            *self = if little_endian {
                f32::from_le_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
            } else {
                f32::from_be_bytes(bytes[..4].try_into().unwrap_or([0; 4]))
            };
        }
    }
}

impl FileVal for f64 {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, little_endian: bool) -> Vec<u8> {
        if little_endian {
            self.to_le_bytes().to_vec()
        } else {
            self.to_be_bytes().to_vec()
        }
    }
    fn file_from_bytes(
        &mut self,
        _stores: &Stores,
        _db_tp: i32,
        little_endian: bool,
        bytes: &[u8],
    ) {
        if bytes.len() >= 8 {
            *self = if little_endian {
                f64::from_le_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            } else {
                f64::from_be_bytes(bytes[..8].try_into().unwrap_or([0; 8]))
            };
        }
    }
}

impl FileVal for String {
    fn file_to_bytes(&self, _stores: &Stores, _db_tp: i32, _little_endian: bool) -> Vec<u8> {
        self.as_bytes().to_vec()
    }
    fn file_from_bytes(
        &mut self,
        _stores: &Stores,
        _db_tp: i32,
        _little_endian: bool,
        bytes: &[u8],
    ) {
        *self = String::from_utf8_lossy(bytes).into_owned();
    }
}

impl FileVal for DbRef {
    /// Serialise a vector (or struct/simple) `DbRef` into bytes for binary file output.
    ///
    /// For `Parts::Vector(elem_tp)` the method iterates every element and delegates to
    /// `Stores::read_data`; for all other types it calls `read_data` on `self` directly.
    fn file_to_bytes(&self, stores: &Stores, db_tp: i32, little_endian: bool) -> Vec<u8> {
        use crate::database::Parts;
        let mut data = Vec::new();
        if let Some(tp_info) = stores.types.get(db_tp as usize) {
            if let Parts::Vector(elem_tp) = tp_info.parts {
                let store = &stores.allocations[self.store_nr as usize];
                let v_rec = store.get_int(self.rec, self.pos) as u32;
                if v_rec != 0 {
                    let length = store.get_int(v_rec, 4) as u32;
                    let elem_size = u32::from(stores.size(elem_tp));
                    for i in 0..length {
                        let elem = DbRef {
                            store_nr: self.store_nr,
                            rec: v_rec,
                            pos: 8 + elem_size * i,
                        };
                        stores.read_data(&elem, elem_tp, little_endian, &mut data);
                    }
                }
            } else {
                stores.read_data(self, db_tp as u16, little_endian, &mut data);
            }
        }
        data
    }

    fn file_from_bytes(
        &mut self,
        _stores: &Stores,
        _db_tp: i32,
        _little_endian: bool,
        _bytes: &[u8],
    ) {
        // Reading directly into a DbRef vector is not currently used by any loft script test.
        // Implement when a test exercises `f#read(n) as vector<T>`.
    }
}

/// Write a value to a loft `File` record.
/// Bytecode equivalent: `State::write_file` in `src/state/io.rs`.
#[allow(clippy::cast_possible_wrap)]
pub fn OpWriteFile<T: FileVal>(stores: &mut Stores, file: DbRef, val: &mut T, db_tp: i32) {
    if file.rec == 0 {
        return;
    }
    let format = stores.store(&file).get_byte(file.rec, file.pos + 32, 0);
    // format: 1=TextFile, 2=LittleEndian, 3=BigEndian, 5=NotExists
    if format != 1 && format != 2 && format != 3 && format != 5 {
        return;
    }
    let little_endian = format == 2;
    let file_ref = file_handle_write(stores, &file);
    if file_ref == i32::MIN {
        return;
    }
    // Track write position: set #index = where this write starts.
    let raw_next = stores.store(&file).get_long(file.rec, file.pos + 16);
    let next_pos = if raw_next == i64::MIN { 0 } else { raw_next };
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 8, next_pos);
    let data = val.file_to_bytes(stores, db_tp, little_endian);
    let written = data.len() as i64;
    if let Some(f) = stores
        .files
        .get_mut(file_ref as usize)
        .and_then(|x| x.as_mut())
        && let Err(e) = f.write_all(&data)
    {
        eprintln!("file write error: {e}");
    }
    // Update #next to reflect the end of this write.
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 16, next_pos + written);
}

/// Read bytes from a loft `File` record into `val`.
/// Bytecode equivalent: `State::read_file` in `src/state/io.rs`.
#[allow(clippy::cast_possible_wrap)]
pub fn OpReadFile<T: FileVal>(
    stores: &mut Stores,
    file: DbRef,
    val: &mut T,
    bytes: i32,
    db_tp: i32,
) {
    if file.rec == 0 {
        return;
    }
    let format = stores.store(&file).get_byte(file.rec, file.pos + 32, 0);
    if format != 1 && format != 2 && format != 3 && format != 5 {
        return;
    }
    let little_endian = format == 2;
    // Track read position: #next holds the byte offset to read from.
    let raw_next = stores.store(&file).get_long(file.rec, file.pos + 16);
    let next_pos = if raw_next == i64::MIN { 0 } else { raw_next };
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 8, next_pos);
    let file_ref = file_handle_read(stores, &file, next_pos);
    if file_ref == i32::MIN {
        return;
    }
    let n = bytes.max(0) as usize;
    let mut buf = vec![0u8; n];
    let is_text = stores.is_text_type(db_tp as u16);
    let nread = if let Some(f) = stores
        .files
        .get_mut(file_ref as usize)
        .and_then(|x| x.as_mut())
    {
        if is_text {
            f.read(&mut buf).unwrap_or(0)
        } else if f.read_exact(&mut buf).is_ok() {
            n
        } else {
            0
        }
    } else {
        0
    };
    buf.truncate(nread);
    val.file_from_bytes(stores, db_tp, little_endian, &buf);
    stores
        .store_mut(&file)
        .set_long(file.rec, file.pos + 16, next_pos + nread as i64);
}

/// Trait allowing `OpRemove` to work with both plain-vector (`i32` index) and
/// sorted/tree (`i64` packed iterator) state variables.
pub trait IterState {
    fn get_cur(&self) -> i32;
    fn set_cur(&mut self, n: i32);
    fn get_finish(&self) -> u32 {
        u32::MAX
    }
    fn set_finish(&mut self, _n: u32) {}
}

impl IterState for i32 {
    fn get_cur(&self) -> i32 {
        *self
    }
    fn set_cur(&mut self, n: i32) {
        *self = n;
    }
}

impl IterState for i64 {
    fn get_cur(&self) -> i32 {
        ((*self as u64) as u32).cast_signed()
    }
    fn set_cur(&mut self, n: i32) {
        let finish = (*self as u64) >> 32;
        *self = ((finish << 32) | u64::from(n as u32)).cast_signed();
    }
    fn get_finish(&self) -> u32 {
        ((*self as u64) >> 32) as u32
    }
    fn set_finish(&mut self, n: u32) {
        let cur = (*self as u64) as u32;
        *self = ((u64::from(n) << 32) | u64::from(cur)).cast_signed();
    }
}

/// Remove the element at the current iterator position and update the iterator
/// so the next step visits the correct successor.
///
/// - `on & 63 == 0`: plain vector — `arg` is the element type index; size is
///   looked up via `stores.get_type(arg as u16).size`.
/// - `on & 63 == 2`: sorted vector — `arg` is the element size in bytes directly.
///
/// Bytecode equivalent: `State::remove` in `src/state/io.rs`.
pub fn OpRemove<S: IterState>(stores: &mut Stores, state: &mut S, data: DbRef, on: i32, arg: i32) {
    let cur = state.get_cur();
    let reverse = (on & 64) != 0;
    match on & 63 {
        0 => {
            // plain vector: arg is the element type index
            let elem_size = u32::from(stores.size(arg as u16));
            let n = if reverse { cur + 1 } else { cur - 1 };
            vector::remove_vector(&data, elem_size, cur, &mut stores.allocations);
            state.set_cur(n);
        }
        1 => {
            // index (red-black tree): arg is the type index; fields offset derived from it
            let cur_u = cur as u32;
            if cur_u == u32::MAX {
                return;
            }
            let tp = arg as u16;
            let fields = stores.fields(tp);
            let cur_ref = iter_ref(&data, cur_u, fields);
            // Compute successor BEFORE removing so tree pointers are still intact.
            let n_after = {
                let store = crate::keys::store(&data, &stores.allocations);
                if reverse {
                    tree::previous(store, &cur_ref)
                } else {
                    tree::next(store, &cur_ref)
                }
            };
            stores.remove(&data, &cur_ref, tp);
            if n_after == 0 {
                // Removed the last element: signal end-of-iteration.
                state.set_finish(u32::MAX);
            } else {
                // Set cur to predecessor of n_after so the next OpStep visits n_after.
                let pred = {
                    let store = crate::keys::store(&data, &stores.allocations);
                    if reverse {
                        tree::next(store, &iter_ref(&data, n_after, fields))
                    } else {
                        tree::previous(store, &iter_ref(&data, n_after, fields))
                    }
                };
                state.set_cur(pred.cast_signed());
                // If n_after equals the finish boundary, signal end-of-iteration.
                if n_after == state.get_finish() {
                    state.set_finish(u32::MAX);
                }
            }
        }
        2 => {
            // sorted vector: arg is the element size in bytes
            if cur < 0 {
                return;
            }
            let n = if reverse { cur + 1 } else { cur - 1 };
            vector::remove_vector(&data, arg as u32, cur, &mut stores.allocations);
            state.set_cur(n);
        }
        _ => {}
    }
}

/// Remove a record from a hash or index collection.
///
/// Bytecode equivalent: `State::hash_remove` in `src/state/io.rs`.
pub fn OpHashRemove(stores: &mut Stores, data: DbRef, rec: DbRef, tp: i32) {
    if rec.rec != 0 {
        stores.remove(&data, &rec, tp as u16);
    }
}

/// Append `count - 1` copies of the last element of `data`, expanding the vector.
///
/// Bytecode equivalent: `State::append_copy` in `src/state/io.rs`.
pub fn OpAppendCopy(stores: &mut Stores, data: DbRef, count: i32, tp: i32) {
    let ctp = stores.content(tp as u16);
    let size = u32::from(stores.size(ctp));
    let length = vector::length_vector(&data, &stores.allocations);
    // Read v_rec before resize; from points to the last existing element.
    let v_rec_before =
        crate::keys::store(&data, &stores.allocations).get_int(data.rec, data.pos) as u32;
    let from = DbRef {
        store_nr: data.store_nr,
        rec: v_rec_before,
        pos: 8 + (length * size - size),
    };
    let multiply = count as u32;
    // Resize to accommodate `multiply` additional elements.
    vector::vector_append(&data, size, &mut stores.allocations);
    stores.vector_set_size(&data, multiply, size);
    // Re-read v_rec in case the resize moved the record.
    let v_rec = crate::keys::store(&data, &stores.allocations).get_int(data.rec, data.pos) as u32;
    for i in 0..(multiply - 1) {
        let to = DbRef {
            store_nr: data.store_nr,
            rec: v_rec,
            pos: 8 + (length + i) * size,
        };
        stores.copy_block(&from, &to, size);
        stores.copy_claims(&data, &to, ctp);
    }
}

/// Wrappers for the `external` module emitted in generated native files.
/// Using these avoids `cfg(feature = "random")` in the generated code.
pub fn cr_rand_seed(seed: i64) {
    #[cfg(feature = "random")]
    crate::ops::rand_seed(seed);
    #[cfg(not(feature = "random"))]
    let _ = seed;
}
#[must_use]
pub fn cr_rand_int(lo: i32, hi: i32) -> i32 {
    #[cfg(feature = "random")]
    {
        crate::ops::rand_int(lo, hi)
    }
    #[cfg(not(feature = "random"))]
    {
        i32::MIN
    }
}

/// Return milliseconds since the Unix epoch (1970-01-01T00:00:00 UTC).
/// Returns `i64::MIN` (null) if the system clock reports a time before the epoch.
/// Bytecode equivalent: `n_now` in `src/native.rs`.
pub fn n_now(_stores: &mut Stores) -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(i64::MIN, |d| d.as_millis() as i64)
}

/// Return microseconds elapsed since program start (monotonic clock).
/// Use for frame timing and benchmarks; unaffected by wall-clock adjustments.
/// Bytecode equivalent: `n_ticks` in `src/native.rs`.
pub fn n_ticks(stores: &mut Stores) -> i64 {
    stores.start_time.elapsed().as_micros() as i64
}

/// Return the platform path separator as a loft character (`i32`).
/// Returns `'/'` (47) on Unix and `'\\'` (92) on Windows.
/// Bytecode equivalent: `n_path_sep` in `src/native.rs`.
pub fn n_path_sep(_stores: &mut Stores) -> i32 {
    crate::platform::sep() as i32
}

/// Read the lock state of the store that owns the record pointed to by `r`.
/// Bytecode equivalent: `n_get_store_lock` in `src/native.rs`.
pub fn n_get_store_lock(stores: &mut Stores, r: DbRef) -> bool {
    stores.is_store_locked(&r)
}

/// Lock or unlock the store that owns the record pointed to by `r`.
/// Bytecode equivalent: `n_set_store_lock` in `src/native.rs`.
pub fn n_set_store_lock(stores: &mut Stores, r: DbRef, locked: bool) {
    if locked {
        stores.lock_store(&r);
    } else {
        stores.unlock_store(&r);
    }
}

/// Return a random integer in `[lo, hi]` (inclusive).
/// Returns `i32::MIN` (null) when `lo > hi` or when the `random` feature is disabled.
/// Bytecode equivalent: `n_rand` in `src/native.rs`.
pub fn n_rand(_stores: &mut Stores, lo: i32, hi: i32) -> i32 {
    #[cfg(feature = "random")]
    {
        crate::ops::rand_int(lo, hi)
    }
    #[cfg(not(feature = "random"))]
    {
        let _ = (lo, hi);
        i32::MIN
    }
}

/// Return a vector of `n` integers `[0, 1, ..., n-1]` in a random order.
/// Returns an empty vector reference when `n <= 0`.
/// Bytecode equivalent: `n_rand_indices` in `src/native.rs`.
#[allow(clippy::cast_possible_wrap)]
pub fn n_rand_indices(stores: &mut Stores, n: i32) -> DbRef {
    let count = if n == i32::MIN || n <= 0 {
        0usize
    } else {
        n as usize
    };
    // Build shuffled index list.
    let mut indices: Vec<i32> = (0..count as i32).collect();
    #[cfg(feature = "random")]
    crate::ops::shuffle_ints(&mut indices);
    // Allocate: vec_rec holds size + data, header_rec holds pointer to vec_rec.
    let base = stores.null();
    let vec_words = ((count as u32 * 4 + 15) / 8).max(1);
    let vec_cr = stores.claim(&base, vec_words);
    let vec_rec = vec_cr.rec;
    let header_cr = stores.claim(&base, 1);
    let header_rec = header_cr.rec;
    {
        let store = stores.store_mut(&base);
        store.set_int(vec_rec, 4, count as i32);
        for (i, &val) in indices.iter().enumerate() {
            store.set_int(vec_rec, 8 + i as u32 * 4, val);
        }
        store.set_int(header_rec, 4, vec_rec as i32);
    }
    DbRef {
        store_nr: base.store_nr,
        rec: header_rec,
        pos: 4,
    }
}

/// Allocate a result vector of `n` elements, each `elem_size` bytes, and run
/// `worker(stores, element_dbref)` on every element, storing the result.
/// For native code, the caller passes a closure that calls the right Rust function.
/// Returns a `DbRef` to the result store; the caller frees it with `OpFreeRef`.
/// Memory layout matches bytecode `n_parallel_for`:
///   header_rec, pos=4 → i32 pointing to vec_rec
///   vec_rec, pos=4    → element count (n)
///   vec_rec, pos=8+i*S → element i  (S = 4 int / 8 long+float / 1 bool bytes)
#[allow(clippy::cast_possible_wrap)]
pub fn n_parallel_for_native<F>(
    stores: &mut Stores,
    input: DbRef,
    elem_size: i32,
    return_size: i32,
    _threads: i32,
    mut worker: F,
) -> DbRef
where
    F: FnMut(&mut Stores, DbRef) -> i64,
{
    let n = vector::length_vector(&input, &stores.allocations) as usize;
    let return_sz = return_size.clamp(1, 8) as u32;
    let result_db = stores.null();
    let vec_words = ((n as u32) * return_sz + 15) / 8;
    let vec_cr = stores.claim(&result_db, vec_words.max(1));
    let vec_rec = vec_cr.rec;
    let header_cr = stores.claim(&result_db, 1);
    let header_rec = header_cr.rec;
    // Collect results.
    let mut fld = 8u32;
    for i in 0..n {
        let elm = {
            let v_rec = crate::keys::store(&input, &stores.allocations)
                .get_int(input.rec, input.pos) as u32;
            DbRef {
                store_nr: input.store_nr,
                rec: v_rec,
                pos: 8 + (i as u32) * (elem_size as u32),
            }
        };
        let val = worker(stores, elm);
        let store = stores.store_mut(&result_db);
        match return_sz {
            8 => {
                store.set_long(vec_rec, fld, val);
            }
            1 => {
                store.set_byte(vec_rec, fld, 0, i32::from(val != 0));
            }
            _ => {
                store.set_int(vec_rec, fld, val as i32);
            }
        }
        fld += return_sz;
    }
    {
        let store = stores.store_mut(&result_db);
        store.set_int(vec_rec, 4, n as i32);
        store.set_int(header_rec, 4, vec_rec as i32);
    }
    DbRef {
        store_nr: result_db.store_nr,
        rec: header_rec,
        pos: 4,
    }
}

/// Read an integer result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_int(stores: &mut Stores, r: DbRef, idx: i32) -> i32 {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_int(r.rec, r.pos) as u32;
    stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_int(v_rec, 8 + (idx as u32) * 4)
}

/// Read a long result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_long(stores: &mut Stores, r: DbRef, idx: i32) -> i64 {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_int(r.rec, r.pos) as u32;
    stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_long(v_rec, 8 + (idx as u32) * 8)
}

/// Read a float result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_float(stores: &mut Stores, r: DbRef, idx: i32) -> f64 {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_int(r.rec, r.pos) as u32;
    let bits = stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_long(v_rec, 8 + (idx as u32) * 8);
    f64::from_bits(bits as u64)
}

/// Read a boolean result element from a `n_parallel_for_native` result vector.
pub fn n_parallel_get_bool(stores: &mut Stores, r: DbRef, idx: i32) -> bool {
    let v_rec = crate::keys::store(&r, &stores.allocations).get_int(r.rec, r.pos) as u32;
    stores
        .store(&DbRef {
            store_nr: r.store_nr,
            rec: v_rec,
            pos: 0,
        })
        .get_byte(v_rec, 8 + idx as u32, 0)
        != 0
}
